### ISSUE TITLE
AWS Error

### ISSUE THREAD

**Issue by tonywong625** [baopham/laravel-dynamodb#1]
Hey there,

I am trying to save (putItem) and item however I am not sure how to specify the type of value using the package.

This is my code:
```
    $model = new \App\Models\dynamoModel();
    $model->id = '2123123123123';
    $model->name = 'Tony';
    $model->save(); 
```
I am getting the following error:
```
DynamoDbException in WrappedHttpHandler.php line 152:
Error executing "PutItem" on "https://dynamodb.us-east-1.amazonaws.com"; AWS HTTP error: Client error: 400 ValidationException (client): One or more parameter values were invalid: Type mismatch for key id expected: N actual: S - {"__type":"com.amazon.coral.validate#ValidationException","message":"One or more parameter values were invalid: Type mismatch for key id expected: N actual: S"}
```

Thanks!

**Comment by tonywong625** [comment]
Just got it working:

Changed my code to the following
```
    $model = new \App\Models\dynamoModel();

    $model->id = 212;
    $model->name = 'Tony;
    $model->save();
```

Changed some code in my model as well

```
class dynamoModel extends DynamoDbModel
{
    protected $table = 'bestjet';

    protected $fillable = ['name'];

    protected $dynamoDbIndexKeys = [
        'S' => 'id',
    ];
}
```

**Comment by baopham** [comment]
@tonywong625  you shouldnt' have to specify `protected $dynamoDbIndexKeys` for the primary key, that property is for global / local indexes. Can you try to use uuid to generate the primary key instead? possibly the marshaler parsed your id to a number.

**Comment by baopham** [comment]
Right, just looked at your code more closely. You had your primary key as a number, try uuid (https://github.com/ramsey/uuid)
