### ISSUE TITLE
Save queue's failed jobs into a DynamoDB table

### ISSUE THREAD

**Issue by Saracevas** [baopham/laravel-dynamodb#100]
I have a project built entirely with DynamoDB and my project makes use of Laravel's queueing and job systems. By default, if a job fails, it tries to connect to the database using the default database connection, which in my case is undefined as the connection is handled by the laravel-dynamodb service provider, and save a record in "failed_jobs" table.

Is there way to bypass this? I want to save the failed jobs to DynamoDB, but modifying the internals of Laravel is obviously a no-go.

Thanks.

**Comment by baopham** [comment]
have you tried the suggestion here https://github.com/laravel/internals/issues/751 overriding queue.failer container.

**Comment by Saracevas** [comment]
I haven't no, but found this for inspiration - [file-queue-failer](https://github.com/pmatseykanets/file-queue-failer). Thanks.
