### ISSUE TITLE
`chunk` fails if there's query scope

### ISSUE THREAD

**Issue by zoul0813** [baopham/laravel-dynamodb#101]
`chunk` calls `getAll` in a loop, which is currently calling `applyScopes`.  Since `chunk` does not create a new query with each loop, the previous scope functions are appended to the current query.  With a basic model that has a single scope attached, `chunk` fails on the 301st call as FilterExpression has a limit of 300 expressions.

A "quick fix" for this is to add an additional parameter to `getAll` that determines whether or not to call `applyScopes`.

```
    protected function getAll($columns = [], $limit = -1, $use_iterator = true, $apply_scopes = true)
    {
        if($apply_scopes) $this->applyScopes();
        // ... trimmed
    }
```

Then modify `chunk`

```
    public function chunk($chunk_size, callable $callback)
    {
        $this->applyScopes();
        while (true) {
            $results = $this->getAll([], $chunk_size, false, false);

            call_user_func($callback, $results);

            if (empty($this->lastEvaluatedKey)) {
                break;
            }
        }
    }
```

**Comment by baopham** [comment]
Could you update the title to: chunk fails if there's query scope
