### ISSUE TITLE
Getting the exception on failure

### ISSUE THREAD

**Issue by hasyimibhar** [baopham/laravel-dynamodb#105]
Is there a way to get the exception from the underlying client? Currently the exception is logged and `false` is returned.

I think it would be better to let the exception pass through and let the caller handle it himself, even though it partially violates the interface of the `save` method.

**Comment by baopham** [comment]
I prefer to follow the interface. But let's see how we can resolve your issue. What are the particular errors that you are trying to catch?

**Comment by zoul0813** [comment]
@baopham - a similar issue came up with a Cognito package I’m contributing too, we ended up making it a config option.  Default swallowed the exception and returned true/false and another option allowed it to throw the exception, a third option introduced an error handler.

We could maybe look into this as an option for dynamodb?

**Comment by baopham** [comment]
Yep good idea @zoul0813 
We can keep it simple:

```php
// dynamodb.php config
return [
   ...,
   // If empty, default to swallow
   // If want to throw, pass in the provided BaoPham\DynamoDb\ErrorHandlers\RaiseError::class
   // If want to handle errors directly, pass in a custom class
   'error_handler' => App\CustomDynamoDbErrorHandler::class
];
```
The above might mean that the custom error handler won't have much context of which method of which class that causes the error though. 

It'd be better if we know more about your use case @hasyimibhar

**Comment by hasyimibhar** [comment]
@baopham I'm saving something to DynamoDb from a queued job. I usually let unexpected exception pass through and halt the job, and I'll get notified (via email, Slack, etc.) of exactly why my job failed.

**Comment by baopham** [comment]
ok, after thinking about it, I think we don't have to catch all exception like how it is right now. Thanks for reporting this, will work on it.

**Comment by baopham** [comment]
Done. Please use v3.0.0
