### ISSUE TITLE
skip/offset support?

### ISSUE THREAD

**Issue by zoul0813** [baopham/laravel-dynamodb#110]
Why do skip and offset throw an exception?

https://github.com/baopham/laravel-dynamodb/blob/246f48fb77a53c36823fbaffe2c98746fc6fa77f/src/DynamoDbQueryBuilder.php#L121

**Comment by baopham** [comment]
Because of

> Unfortunately, offset of how many records to skip does not make sense for DynamoDb. Instead, provide the last result of the previous query as the starting point for the next query.

**Comment by zoul0813** [comment]
Ahh, ok... I get it.  Introducing after as an alternative to skip/offset because of the expectation that skip/offset has.
