### ISSUE TITLE
How can we do batch insert in dynamodb using laravel

### ISSUE THREAD

**Issue by saurabh147sharma** [baopham/laravel-dynamodb#115]
I don't find any function for batch insert.

**Comment by baopham** [comment]
Because it's not supported yet :)

**Comment by vigikaran** [comment]
batchWriteItem is now supported  ,

**Comment by baopham** [comment]
What I meant is it is not supported yet in this library.

**Comment by baopham** [comment]
v4.7.0 now adds `DynamoDb` facade which allows you to build raw queries more easily. You can use it to do batch insert since there is no equivalent way in Eloquent. 

So something like this, assuming you want to do batch insert into one table:

```php
$tableName = 'foobar';
$putRequests = [];

for ($items as $item) {
	$query = DynamoDb::newQuery()
  		->setItem(DynamoDb::marshalItem($item))
		->prepare()
		->query;
	$putRequests[] = ['PutRequest' => $query];
}

$results = DynamoDb::newQuery()
	->setRequestItems([$tableName => $putRequests])
	->prepare()
	->batchWriteItem();
```

**Comment by domenicozinzidea** [comment]
Thanks for the advice it was very helpful. I just have a problem some lines are not saved correctly in DynamoDB. Is it just my problem?
