### ISSUE TITLE
WhereIn or Where('id','in',$array) Fail

### ISSUE THREAD

**Issue by hoanghapo** [baopham/laravel-dynamodb#116]
I cant `where in` in model.
"IN is not supported for KeyConditionExpression" error message.

**Comment by baopham** [comment]
Because you're using `id` (primary key) in the condition. It's better to use `BatchGetItem` in this case (which this library is not yet supported) or you can loop through each `id`:

```php
foreach ($ids as $id) {
  $model->find($id);
}
```
which is not optimal compared to `BatchGetItem`

**Comment by hoanghapo** [comment]
@baopham 
I use
```
$dataTags = new Tag();
            foreach ($tagTopicIds as $value){
                $dataTags = $dataTags->orWhere('id',$value);
            }
            $dataTags = $dataTags->get();
```
okay?

**Comment by baopham** [comment]
Try this:

```php
$query = Tag::newQuery();

foreach ($tagTopicIds as $id) {
   $query->orWhere('id', $id);
}

$tags = $query->get();
```
