### ISSUE TITLE
How to orderBy

### ISSUE THREAD

**Issue by hoanghapo** [baopham/laravel-dynamodb#117]
i want orderBy topic_id or created_at DESC
defaul index is ASC
```
$query = Comment::where('topic_id', $topicId)
            ->where('created_at', '>=', 0)
->orderBy($conditions['orderBy']);
```

![screen shot 2018-01-02 at 15 31 37](https://user-images.githubusercontent.com/22829982/34478186-0f7adbc6-efd2-11e7-8811-0870bc4f5728.png)

**Comment by hoanghapo** [comment]
use it, oke? where to insert?
```
$query['ScanIndexForward'] = strtolower($this->orderBy) == 'desc' ? false : true;
```

**Comment by baopham** [comment]
Specifying the order is not yet supported. Let me see what can be done.

**Comment by hoanghapo** [comment]
```
Specifying the order is not yet supported. Let me see what can be done.
```
I wait for your feedback.

**Comment by baopham** [comment]
I won't have time until this weekend unfortunately

**Comment by baopham** [comment]
Please try version `4.2.0` and follow the instruction [here](https://github.com/baopham/laravel-dynamodb#decorate-query)

**Comment by sobwoofer** [comment]
@baopham 4.2.0 ? but 4.1.2 is latest version for today
