### ISSUE TITLE
Bug when register validate

### ISSUE THREAD

**Issue by hoanghapo** [baopham/laravel-dynamodb#118]
when validate register 
![screen shot 2018-01-02 at 16 10 26](https://user-images.githubusercontent.com/22829982/34479178-b5bcdbc4-efd7-11e7-97b8-cbe12118aa72.png)

when validate `NE` email
![screen shot 2018-01-02 at 16 14 01](https://user-images.githubusercontent.com/22829982/34479221-fe591a3c-efd7-11e7-963f-ce61de561adb.png)

How to fix it

**Comment by baopham** [comment]
Validator is not within the scope of this project. Keep in mind that this is DynamoDB so not all SQL queries can be mapped directly to DynamoDB queries. So, you will need to implement your own validation.
