### ISSUE TITLE
I am trying to order ASC the result of a query but dont work.. 

### ISSUE THREAD

**Issue by jabzumnd** [baopham/laravel-dynamodb#124]
I'm trying to do a chat with dynamodb and laravel and just this library I see it very well .. The thing is that I'm doing a search in ASC order the insertion date. I'm doing this with my code:

`$chat_messages = ProyectorChatMessage::where('idcobertura',1)
        ->orWhere('idcobertura', 2)
        ->decorate(function (RawDynamoDbQuery $raw) {
            // desc order
            $raw->query['insert_date'] = false;
        })
        ->get();`

And it returns an error to me when using the RawDynamoDbQuery object, what could it be?

> Argument 1 passed to App\Http\Controllers\AwsController::App\Http\Controllers\{closure}() must be an instance of App\Http\Controllers\RawDynamoDbQuery, instance of BaoPham\DynamoDb\RawDynamoDbQuery given

**Comment by baopham** [comment]
You didn't import the class. Put this on top

```php
use BaoPham\DynamoDb\RawDynamoDbQuery;
```

And btw, I suggest you check out DynamoDb docs on how to do ordering because that's not how you do it.

**Comment by jabzumnd** [comment]
Thank you, importing the class work with me..

I am now trying to sort my data in ascending or descending order by "creation date". I understand that my IndexKeys I have to put them in my model. I have it in the following way:

```
protected $dynamoDbIndexKeys = [
        'idcobertura-fecha_insercion-index' => [
            'hash' => 'idcobertura',
            'range' => 'fecha_insercion'
        ]
    ];
```


When I want to do the following query, everything works fine with its ordering by setting false or true the ScanIndexForward property.

```
$chat_messages = ProyectorChatMessage::where('idcobertura',2)
        ->where('fecha_insercion','>=', '2018-01-25 00:00:00')
        ->decorate(function (RawDynamoDbQuery $raw) {
            $raw->query['ScanIndexForward'] = false;
        })
        ->withIndex('idcobertura-fecha_insercion-index')
        ->get();
```

Here everything works fine and returns the following information:

> string (19) "2018-01-26 09:59:22"
> string (19) "2018-01-26 09:58:22"
> string (19) "2018-01-26 09:58:20"
> string (19) "2018-01-26 09:58:16"
> string (19) "2018-01-25 19:34:38"
> string (19) "2018-01-25 19:32:54"
> string (19) "2018-01-25 18:06:58"
> string (19) "2018-01-25 18:06:33"
> string (19) "2018-01-25 18:06:13"
> string (19) "2018-01-25 09:57:37"

Now when I want to make a range between two dates with the following query, the return of the information fails and does not order it as expected:

```
$chat_messages = ProyectorChatMessage::where('idcobertura',2)
        ->where('fecha_insercion','>=', '2018-01-25 00:00:00')
        ->where('fecha_insercion', '<=', '2018-01-26 23:59:59')
        ->decorate(function (RawDynamoDbQuery $raw) {
            $raw->query['ScanIndexForward'] = false;
        })
        ->withIndex('idcobertura-fecha_insercion-index')
        ->get();
```

Return request:

> string (19) "2018-01-25 18:06:58"
> string (19) "2018-01-25 19:32:54"
> string (19) "2018-01-25 19:34:38"
> string (19) "2018-01-25 09:57:37"
> string (19) "2018-01-26 09:58:16"
> string (19) "2018-01-26 09:58:20"
> string (19) "2018-01-26 09:58:22"
> string (19) "2018-01-26 09:59:22"
> string (19) "2018-01-25 18:06:13"
> string (19) "2018-01-25 18:06:33"


Maybe you can use the following screens:

![screenshot from 2018-01-26 11-39-19](https://user-images.githubusercontent.com/17731030/35452918-e6dfd706-028d-11e8-8143-6f00881f2900.png)
![screenshot from 2018-01-26 11-39-00](https://user-images.githubusercontent.com/17731030/35452919-e6f48174-028d-11e8-9ca0-8bcc4152dea6.png)

**Comment by baopham** [comment]
Thanks for such detailed explanations!

1. Could you show me the output of this:

```php
$query = ProyectorChatMessage::where('idcobertura',2)
        ->where('fecha_insercion','>=', '2018-01-25 00:00:00')
        ->where('fecha_insercion', '<=', '2018-01-26 23:59:59')
        ->decorate(function (RawDynamoDbQuery $raw) {
            $raw->query['ScanIndexForward'] = false;
        })
        ->withIndex('idcobertura-fecha_insercion-index')
        ->toDynamoDbQuery();

print_r($query);
```

2. I suspect the library fails to detect a `Query` operation. If so, you could force it like so:

```php
        ->decorate(function (RawDynamoDbQuery $raw) {
			$raw->op = 'Query';
            $raw->query['ScanIndexForward'] = false;
        })
```
see if that changes anything.

**Comment by baopham** [comment]
Ah, also try this:

```php
        ->decorate(function (RawDynamoDbQuery $raw) {
			$raw->op = 'Query';
            $raw->query['ScanIndexForward'] = false;
			$raw->query['KeyConditionExpression'] = "#fecha_insercion >= :a2";
			$raw->query['FilterExpression'] = "#fecha_insercion <= :a3";
        })
```

**Comment by jabzumnd** [comment]
Thanks you for your effort to answer me, i really appreciate it.

Ok..

1) Print the $query with ->toDynamoDbQuery();

> Response: print_r($query): 
> BaoPham\DynamoDb\RawDynamoDbQuery Object ( [op] => Scan [query] => Array ( [FilterExpression] => #idcobertura = :a1 AND #fecha_insercion >= :a2 AND #fecha_insercion <= :a3 [ExpressionAttributeNames] => Array ( [#idcobertura] => idcobertura [#fecha_insercion] => fecha_insercion ) [ExpressionAttributeValues] => Array ( [:a1] => Array ( [N] => 2 ) [:a2] => Array ( [S] => 2018-01-25 00:00:00 ) [:a3] => Array ( [S] => 2018-01-26 23:59:59 ) ) [TableName] => proyector_chat_message ) [array:BaoPham\DynamoDb\RawDynamoDbQuery:private] => Array ( [0] => Scan [1] => Array ( [FilterExpression] => #idcobertura = :a1 AND #fecha_insercion >= :a2 AND #fecha_insercion <= :a3 [ExpressionAttributeNames] => Array ( [#idcobertura] => idcobertura [#fecha_insercion] => fecha_insercion ) [ExpressionAttributeValues] => Array ( [:a1] => Array ( [N] => 2 ) [:a2] => Array ( [S] => 2018-01-25 00:00:00 ) [:a3] => Array ( [S] => 2018-01-26 23:59:59 ) ) ) ) ) 


2) Trying to force a Query operation. It gives me an error:

> (2/2) DynamoDbException
> Error executing "Query" on "https://dynamodb.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://dynamodb.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response:
> {"__type":"com.amazon.coral.validate#ValidationException","message":"Either the KeyConditions or KeyConditionExpression (truncated...)
> ValidationException (client): Either the KeyConditions or KeyConditionExpression parameter must be specified in the request. - {"__type":"com.amazon.coral.validate#ValidationException","message":"Either the KeyConditions or KeyConditionExpression parameter must be specified in the request."}


This is how I did it:
```
$chat_messages = ProyectorChatMessage::where('idcobertura',2)
        ->where('fecha_insercion','>=', '2018-01-25 00:00:00')
        ->where('fecha_insercion', '<=', '2018-01-26 23:59:59')
        ->decorate(function (RawDynamoDbQuery $raw) {
			$raw->op = 'Query';
            $raw->query['ScanIndexForward'] = false;
        })
        ->withIndex('idcobertura-fecha_insercion-index')
        ->get();
```

3) Answer to "Ah, also try this:" It gives me another error:

> (2/2) DynamoDbException
> Error executing "Query" on "https://dynamodb.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://dynamodb.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response:
> {"__type":"com.amazon.coral.validate#ValidationException","message":"Value provided in ExpressionAttributeNames unused i (truncated...)
> ValidationException (client): Value provided in ExpressionAttributeNames unused in expressions: keys: {#idcobertura} - {"__type":"com.amazon.coral.validate#ValidationException","message":"Value provided in ExpressionAttributeNames unused in expressions: keys: {#idcobertura}"}


I appreciate your help, I hope this library can solve what I want :).

**Comment by baopham** [comment]
4. Try this:

```php
		->decorate(function (RawDynamoDbQuery $raw) {
			$raw->op = 'Query';
            $raw->query['ScanIndexForward'] = false;
			$raw->query['KeyConditionExpression'] = "#idcobertura = :a1 AND #fecha_insercion >= :a2";
			$raw->query['FilterExpression'] = "#fecha_insercion <= :a3";
        })
```

**Comment by jabzumnd** [comment]
Hi..

I think that trying to force "Query" to execute is the problem at this moment, the code returns this message: 

> (2/2) DynamoDbException
> Error executing "Query" on "https://dynamodb.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://dynamodb.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response:
> {"__type":"com.amazon.coral.validate#ValidationException","message":"Query condition missed key schema element: idchat_m (truncated...)
> ValidationException (client): Query condition missed key schema element: idchat_message - {"__type":"com.amazon.coral.validate#ValidationException","message":"Query condition missed key schema element: idchat_message"}

Annex code:
```
$chat_messages = ProyectorChatMessage::where('idcobertura',2)
            ->where('fecha_insercion','>=', '2018-01-25 00:00:00')
            ->where('fecha_insercion', '<=', '2018-01-26 23:59:59')
            ->decorate(function (RawDynamoDbQuery $raw) {
    			$raw->op = 'Query'; //<-- I think here is the problem
                        $raw->query['ScanIndexForward'] = false;
    			$raw->query['KeyConditionExpression'] = "#idcobertura = :a1 AND #fecha_insercion >= :a2";
    			$raw->query['FilterExpression'] = "#fecha_insercion <= :a3";
            })
            ->withIndex('idcobertura-fecha_insercion-index')
            ->get();

```

**Comment by baopham** [comment]
Well `ScanIndexForward` only works with `Query`. Seems like your condition is missing the hash key?

Can you list out your:

* Hash key
* Range key
* All global/local index

**Comment by jabzumnd** [comment]
Yes, you are absolutely right, I should not forget my "hash key" for those queries, since my table was defined as follows:

![screenshot from 2018-01-29 10-19-39](https://user-images.githubusercontent.com/17731030/35521199-c6e99592-04de-11e8-85c9-7441f7f09fff.png)


I did the query making idchat_message greater than 0 (it will always be):

```
$chat_messages = ProyectorChatMessage::where('idcobertura',2)
            ->where('fecha_insercion','>=', '2018-01-25 00:00:00')
            ->where('fecha_insercion', '<=', '2018-01-26 23:59:59')
            ->where('idchat_message','>','0')
            ->decorate(function (RawDynamoDbQuery $raw) {
    			$raw->op = 'Query';
                $raw->query['ScanIndexForward'] = true;
    			$raw->query['KeyConditionExpression'] = "#idcobertura = :a1 AND #idchat_message > :a4";
    			$raw->query['FilterExpression'] = "#fecha_insercion <= :a3 AND #fecha_insercion >= :a2";
            })
            ->withIndex('idcobertura-fecha_insercion-index')
            ->get();
```
The result is how I expect it:

> string(19) "2018-01-25 18:06:58" 
> string(19) "2018-01-25 19:32:54" 
> string(19) "2018-01-25 19:34:38" 
> string(19) "2018-01-25 09:57:37" 
> string(19) "2018-01-26 09:58:16" 
> string(19) "2018-01-26 09:58:20" 
> string(19) "2018-01-26 09:58:22" 
> string(19) "2018-01-26 09:59:22" 
> string(19) "2018-01-25 18:06:13" 
> string(19) "2018-01-25 18:06:33" 


What I do not finish to understand is: why I have to take into account the "sort key" that I defined at the beginning, since I am indicating that I am going to work with another index that has nothing to do with 'idchat_message'... I am working with 

> ->withIndex('idcobertura-fecha_insercion-index')


Look my $dynamoDbIndexKeys:
```
 protected $dynamoDbIndexKeys = [
        'idcobertura-fecha_insercion-index' => [
            'hash' => 'idcobertura',
            'range' => 'fecha_insercion'
        ]
    ];
```

For the moment I will work with what we manage to solve.

Thank you very much baopham.

**Comment by jabzumnd** [comment]
Mmm. no, the result is not how I expect it .. I realized that they come scrambled the same .. :(

> string(19) "2018-01-25 18:06:58" 
> string(19) "2018-01-25 19:32:54" 
> string(19) "2018-01-25 19:34:38" 
> string(19) "2018-01-25 09:57:37" 
> string(19) "2018-01-26 09:58:16" 
> string(19) "2018-01-26 09:58:20" 
> string(19) "2018-01-26 09:58:22" 
> string(19) "2018-01-26 09:59:22" 
> string(19) "2018-01-25 18:06:13" 
> string(19) "2018-01-25 18:06:33" 

I do not know what's happening here, my friend ..

**Comment by baopham** [comment]
I'm not surprised that it doesn't work. 

Let's move the conversation here: https://gitter.im/laravel-dynamodb/Lobby

**Comment by baopham** [comment]
Before v4.2.2:

```php
		$msgs = ProyectorChatMessage::where('idcobertura',2)
            ->where('fecha_insercion', 'BETWEEN', ['2018-01-25 00:00:00', '2018-01-26 23:59:59'])
            ->decorate(function (RawDynamoDbQuery $raw) {
    			$raw->op = 'Query';
                $raw->query['ScanIndexForward'] = true;
    			$raw->query['KeyConditionExpression'] = 'idcobertura = :a1 AND fecha_insercion BETWEEN :a2 AND :a3';
				$raw->query['IndexName'] = 'idcobertura-fecha_insercion-index';
            })
            ->get();
```

For v4.2.2 and above:

```php
		$msgs = ProyectorChatMessage::where('idcobertura',2)
            ->where('fecha_insercion', 'BETWEEN', ['2018-01-25 00:00:00', '2018-01-26 23:59:59'])
			->withIndex('idcobertura-fecha_insercion-index')
            ->decorate(function (RawDynamoDbQuery $raw) {
    			$raw->op = 'Query';
                $raw->query['ScanIndexForward'] = true;
    			$raw->query['KeyConditionExpression'] = 'idcobertura = :a1 AND fecha_insercion BETWEEN :a2 AND :a3';
            })
            ->get();
```

**Comment by jabzumnd** [comment]
Solved.!! Thank you baopham.!!

**Comment by baopham** [comment]
👍 👍
