### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by jilster** [baopham/laravel-dynamodb#130]
Hi! I am upgrading to Laravel 5.6 and laravel-dynamodb is expecting Laravel 5.5.*. I know Laravel 5.6 is very fresh (released yesterday), but are there any plans for supporting it? It would be great if there were. Thanks in advance!

**Comment by baopham** [comment]
We just need to do a thorough testing and ensure 5.6 didn't introduce any breaking changes for us. Feel free to make a PR and test.

**Comment by jilster** [comment]
Done: https://github.com/baopham/laravel-dynamodb/pull/131

But like i said in the description of the PR itself, it works for me and i don't expect any problems, but my application does not use all functionality in laravel-dynamodb.
