### ISSUE TITLE
Using with Lumen : Missing required client configuration options

### ISSUE THREAD

**Issue by jaseyd** [baopham/laravel-dynamodb#134]
Hi. Just a heads up for anyone using this with Lumen.

I kept getting this annoying error about missing configuration options. Eventually I traced it back to the vendor published 'dynamodb.php' not being added to the config.

To resolve this, I added the following in bootstrap/app.php

`$app->configure('dynamodb');`

Hope this helps someone.

Cheers for a great library!
Jason

**Comment by baopham** [comment]
Cool! Thanks for taking the time to create an issue. 

There is an open PR for Lumen instruction https://github.com/baopham/laravel-dynamodb/pull/125/files that I haven't had time to verify. Feel free to comment or create a new PR for the README.

Thanks again!

**Comment by baopham** [comment]
I guess this can be closed now.

**Comment by baopham** [comment]
See #136
