### ISSUE TITLE
Remove folder dynamodb_local as it increases significantly the repository size

### ISSUE THREAD

**Issue by adrian7** [baopham/laravel-dynamodb#135]
I think we should remove the folder containing dynamodb_local, and add instead instructions on how to get DynamoDb running locally, or provide a docker-compose file with the service.

**Comment by baopham** [comment]
👌 I'll think of something. Thanks for the suggestions.

**Comment by baopham** [comment]
I've made `dynamodb_local` excluded from archive so that the package is smaller when being installed. I still prefer to have it in the repo for now. It's more convenient (less step to setup for local development) for me or anyone who wants to contribute.
