### ISSUE TITLE
the delete() issue seen before. 

### ISSUE THREAD

**Issue by kevinyea** [baopham/laravel-dynamodb#137]
Hi all
Resorted to Tinker as can't get delete to work.
I can satisfy a 'where' and prove that using get() or first() as per below. But there is no way with that record I can delete().
If the item retrieval functions works, surely then I should be able to delete the item?
The primary partition key is used in the example below (pivot_uuid) but I can't do model->delete() or model->first()->delete() or get()[0]->delete().

Any clue will be most appreciated. Thanks
Kevin

`>>> $p=App\vPivot::where('pivot_uuid','a1d9012c-16d4-4f14-90cd-ec21d6907d87')->First()
=> App\vPivot {#1410
     user_uuid: "abbecc96-d043-47c8-aae2-c1c14cb249e6",
     updated_at: "2018-03-24T19:05:57+00:00",
     pivot_uuid: "a1d9012c-16d4-4f14-90cd-ec21d6907d87",
     created_at: "2018-03-24T19:05:57+00:00",
     team_uuid: "123-456-7788-9101",
   }
>>> $p=App\vPivot::where('pivot_uuid','a1d9012c-16d4-4f14-90cd-ec21d6907d87')->Delete()
Aws\DynamoDb\Exception\DynamoDbException with message 'Error executing "DeleteItem" on "https://dynamodb.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://dynamodb.eu-west-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"com.amazon.coral.validate#ValidationException","message":"The provided key element does not match the schema" (truncated...)
 ValidationException (client): The provided key element does not match the schema - {"__type":"com.amazon.coral.validate#ValidationException","message":"The provided key element does not match the schema"}'
>>> $p=App\vPivot::where('pivot_uuid','a1d9012c-16d4-4f14-90cd-ec21d6907d87')->First()->Delete()
Aws\DynamoDb\Exception\DynamoDbException with message 'Error executing "DeleteItem" on "https://dynamodb.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://dynamodb.eu-west-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"com.amazon.coral.validate#ValidationException","message":"The provided key element does not match the schema" (truncated...)
 ValidationException (client): The provided key element does not match the schema - {"__type":"com.amazon.coral.validate#ValidationException","message":"The provided key element does not match the schema"}'
>>> 
`

**Comment by kevinyea** [comment]
Apologies.
It was 
protected $primaryKey = 'pivot_uuid';
Not declared properly.

**Comment by baopham** [comment]
Nice debugging! Glad it's resolved now.
