### ISSUE TITLE
Implement refresh()

### ISSUE THREAD

**Issue by adrian7** [baopham/laravel-dynamodb#139]
Looks like `refresh()` method is missing from `DynamoDbModel`, leading to asking the relational db for the model.

**Comment by baopham** [comment]
Yes, we don't have `refresh` yet

> leading to asking the relational db for the model.
What do you mean by this?

**Comment by adrian7** [comment]
@baopham when you have both a relational database and DynamoDb configured, then the Elonquent's Model refresh gets called.

**Comment by baopham** [comment]
Done, it is now in version 4.5.0
