### ISSUE TITLE
 DynamoDbQueryBuilder.php line 499 error

### ISSUE THREAD

**Issue by johnbabu** [baopham/laravel-dynamodb#140]
Why there is three dots in function argument on line number 499? It's throwing error.

![image](https://user-images.githubusercontent.com/987106/41053481-454869e0-69d9-11e8-8bd7-629048cb0694.png)

![image](https://user-images.githubusercontent.com/987106/41053500-5c34f272-69d9-11e8-9445-bd2fef4d7262.png)

**Comment by baopham** [comment]
It's the [splat operator](https://lornajane.net/posts/2014/php-5-6-and-the-splat-operator). Are you on at least php5.6?

**Comment by johnbabu** [comment]
Oops I'm using php 5.5.9. I will upgrade my PHP and let you know if this exist. 

Thanks for quick reply

**Comment by johnbabu** [comment]
It's working perfectly in PHP 5.6. Thanks a lot :)
