### ISSUE TITLE
I can not connect without credentials

### ISSUE THREAD

**Issue by gerardo-junior** [baopham/laravel-dynamodb#145]
I have envs with direct access to the dynamo (without credentials) I can connect with sdk only and with sh aws commad but with laravel-dynamodb deleting credentials or leaving null result : {"__type": "com.amazon.coral.service # UnrecognizedClientException "," message ":" The security token included in the request i (truncated ...)

Laravel: 5.6
laravel-dynamodb: 4.6
```php
    'connections' => [
        'aws' => [
            
            'region' => env('DYNAMODB_REGION'),
            'debug' => env('APP_DEBUG', false),
            
        ],
    
        'local' => [
            'credentials' => [
                'key' => 'dynamodb_local',
                'secret' => 'secret',
            ],
            'region' => 'stub',
            'endpoint' => env('DYNAMODB_ENDPOINT'),
            'debug' => env('APP_DEBUG', false),
        ],

        'test' => [
            'endpoint' => env('DYNAMODB_ENDPOINT'),
            'debug' => env('APP_DEBUG', false),
        ],
    ],
];
```

**Comment by gerardo-junior** [comment]
Okay, my problem is something wrong with my curl

I'm sorry, u can close

**Comment by baopham** [comment]
Awesome! Thank you for the update.
