### ISSUE TITLE
No Exception Thrown , when inserting duplicate composite data.

### ISSUE THREAD

**Issue by koushikSen** [baopham/laravel-dynamodb#146]
When using in the eloquent method, 
`<?php 
...
....
echo     $qaMemory->save();    
echo    $memory->save();`
...
...
?>
both return true, whereas I am saving data in qaMemory that I already have in the attached table. it should throw some exception or any value by which I can make an error handling operation.

Can any 1 share some view in this matter?

**Comment by zoul0813** [comment]
Can you provide your schema (the class in laravel and the schema in dynamodb itself).

Can you also provide a more detail description of what is being saved, so we can reproduce the issue and repeat it?

**Comment by baopham** [comment]
@koushikSen 

That's pretty good observation. Thanks for flagging. You don't have to worry about double inserting as DynamoDB always looks as the key to determine the uniqueness. As `save` uses [PutItem](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-dynamodb-2012-08-10.html#putitem), the second call will just replace the record with the exact same values.

`save` here can be used in both contexts of inserting and updating. So I would think the current behaviour is ok - e.g. when you update something twice, you wouldn't expect the second call to fail.

I'll close this for now. Feel free to leave more comments.
