### ISSUE TITLE
Call to undefined method BaoPham\DynamoDb\DynamoDbQueryBuilder::whereNotNull()

### ISSUE THREAD

**Issue by koushikSen** [baopham/laravel-dynamodb#147]
Hi
I have the following code

`<?php 
namespace App\Models;
use BaoPham\DynamoDb\DynamoDbModel;
Class DynamoDbMemories extends DynamoDbModel{
    protected $table = 'table_name';
    protected $guarded = [];
    protected $dates = ['deleted_at'];
    protected $primaryKey = 'user_id';
    protected $compoite_key = ['user_id','label'];
} ?>` 

in Controller I have 
` public function index()
    {
        $user_id = Auth::user()->id;
        $memory = new Memory();        
        $memory = $memory->where('user_id',$user_id)->whereNotNull('label')->get();
        return view('home')->with(compact('memory'));
    }`
this produces the error  "Call to undefined method BaoPham\DynamoDb\DynamoDbQueryBuilder::whereNotNull(). 
What to do now?

**Comment by baopham** [comment]
Hi @koushikSen, is it resolved now?

**Comment by koushikSen** [comment]
yes
