### ISSUE TITLE
[Feature Request] Async Request support

### ISSUE THREAD

**Issue by sahilsharma011** [baopham/laravel-dynamodb#148]
Is there any plan or roadmap for supporting asynchronous workflows using Eloquent models which have been included in PHP SDK for AWS v3  
I can also contribute for this feature if you can show me a roadmap

**Comment by baopham** [comment]
Great suggestion! I'd love for it to be in the roadmap.

Do you have a proposal what would the API looks like? e.g. are you suggesting we have something like this: `$model->saveAsync()`, `$model->where(...)->getAsync()`? I don't think Eloquent has an async syntax.

**Comment by baopham** [comment]
Sounds good. Feel free to create a PR. I'll resume working on this next weekend.

**Comment by sahilsharma011** [comment]
Okay I have cloned the project and I'll try to work on a PR. Can you guide me a bit through this.  
First I am working on a `saveAsync` method which will call a new `saveAsync` method in `DynamoDbQueryBuilder` class and this method will be making use of `putItemAsync` which comes with aws php sdk. It will return a promise which will be returned back to where the initial save call was made where the user will wait for this promise resolution as per their needs.  
Does this sound good

**Comment by baopham** [comment]
Yep that sounds about right. The flow should be similar to `save`. You can start with `saveAsync` first. For tests, you will need to add `testSaveAsync` in both `DynamoDbCompositeModelTest` and `DynamoDbNonCompositeModelTest`.

Thanks for working on this!

**Comment by baopham** [comment]
🎉  #150
