### ISSUE TITLE
Scan used instead of query

### ISSUE THREAD

**Issue by sahilsharma011** [baopham/laravel-dynamodb#149]
**Describe the bug**
Eloquent queries are using 'scan' whenever I use where function.  

**Schema**
```
use BaoPham\DynamoDb\DynamoDbModel;

class DistributorInvoices extends DynamoDbModel
{
    protected $table = 'mytable';
    protected $dynamoDbIndexKeys = [
        'GSIndex' => [
            'hash' => 'hashkey',
            'range' => 'rangekey',
        ]
    ];

```
My Query
```
DynamoModel::where('hashkey',$hash)
                ->where('rangekey','between',[$range1,$range2])
                ->withIndex('GSIndex')
                ->toDynamoDbQuery();
```
**Debug info**
And this is what is returned when I dump the DynamoDbQuery.
```
RawDynamoDbQuery {#575
  +op: "Scan"
  +query: array:5 [
    "FilterExpression" => "#hash = :a1 AND (#range BETWEEN :a2 AND :a3)"
    "ExpressionAttributeNames" => array:2 [
      "#hash" => "hashkey"
      "#range" => "rangekey"
    ]
    "ExpressionAttributeValues" => array:3 [
      ":a1" => array:1 [
        "N" => "2"
      ]
      ":a2" => array:1 [
        "N" => "1531938600"
      ]
      ":a3" => array:1 [
        "N" => "1532024999"
      ]
    ]
    "TableName" => "mytable"
    "IndexName" => "GSIndex"
  ]
}
```

**Comment by baopham** [comment]
Good catch. Thanks for reporting. This should be a quick fix

**Comment by baopham** [comment]
hm... what version are you on? I'm not getting the same result: https://github.com/baopham/laravel-dynamodb/commit/a244362835fff63b78b989d09e3550ebaa449abc - the test passed for me.

**Comment by sahilsharma011** [comment]
I dig into the code a little bit and I found out that array_first laravel helper function was being used in Analyzer.php  
This function was modified in laravel 5.3 where order of its parameters was reversed and that is why it is not working with my code because I have Laravel 5.2  
[Arrays - Key / Value Order Change](https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0)

**Comment by baopham** [comment]
Ugh, this is the third time with laravel's helpers. I'll update that so it can be compatible with Laravel 5.2. Thanks for digging in the code!

**Comment by baopham** [comment]
This should be fixed now. Could you take a look? Thanks!

**Comment by sahilsharma011** [comment]
Yes it works fine now. Thank you. 
Which laravel versions do you plan to support and will you be abandoning support from Laravel 5.2 any time soon?

**Comment by baopham** [comment]
I'm not planning to abandon support for Laravel 5.2 anytime soon. It's just that I'm actively developing in the latest(?) Laravel version so I didn't catch this bug. I'm going to have a task to migrate all the Laravel helpers I've used to the new class. PRs are welcome!
