### ISSUE TITLE
Need Sql table

### ISSUE THREAD

**Issue by ebisbe** [baopham/laravel-dynamodb#15]
Hello,

Why is not explained that in order to work the paginate it needs the table at MySql?? I've been having lot of struggle with make it work for that reason. 

And your dynamo local box is not working for me neither.
java -Djava.library.path=./DynamoDBLocal_lib -jar vendor/baopham/dynamodb/dynamodb_local/DynamoDBLocal.jar --port 3000 -inMemory

**Comment by baopham** [comment]
Hi. Pagination is not supported and what do you mean the dynamo local box is not working? what errors do you see?

**Comment by ebisbe** [comment]
Hello, 
What do you mean with pagination is not suported? I've been doing a lot of tests and if you have a mysql table you can paginate all the values from the DynamoDB table. 
From the local box I don't get any errors on startup but when I try to PutItem() is not working. With the one downloaded from the Aws is working fine. 

As this seems a bit unclear I'll create a new project with all things in order to show to you. I hope tomorrow I have it.

**Comment by baopham** [comment]
I can tell you that dynamo pagination is not supported in this library yet. It seems working to you with the MySQL table trick but that's not how it's supposed to work.

As for the local dynamo, do you have this in your `.env`?

```
DYNAMODB_LOCAL=true
DYNAMODB_LOCAL_ENDPOINT=http://localhost:3000
```

You should look at your logs `storage/logs/laravel.log`, it gives you more info.

**Comment by ebisbe** [comment]
Ok, it's not supported but it works.

Yes I have that configuration and is not working.

**Comment by baopham** [comment]
Ok. What you have is rather hacky but pagination is on my todo list.

Please give errors you get from `storage/logs/laravel.log` when you save something.

**Comment by ebisbe** [comment]
Next exception 'Aws\DynamoDb\Exception\DynamoDbException' with message 'Error executing "CreateTable" on "http://localhost:8000"; AWS HTTP error: cURL error 7: Failed to connect to localhost port 8000: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /var/www/adinton_2/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:159
Stack trace:

**Comment by ebisbe** [comment]
Have you think of converting this wrapper to a connection like the mongoDB?

**Comment by ebisbe** [comment]
That's the error I get 

[Aws\DynamoDb\Exception\DynamoDbException]
  Error executing "PutItem" on "http://localhost:3000"; AWS HTTP error: Server error: `POST http://localhost:3000` resulted in a `500 Server Error` response:
  {"__type":"com.amazonaws.dynamodb.v20120810#InternalFailure","Message":"The request processing has failed because of an  (truncated...)
   InternalFailure (server): The request processing has failed because of an unknown error, exception or failure. - {"__type":"com.amazonaws.dynamodb.v20120810#InternalFailure"
  ,"Message":"The request processing has failed because of an unknown error, exception or failure."}



  [GuzzleHttp\Exception\ServerException]
  Server error: `POST http://localhost:3000` resulted in a `500 Server Error` response:
  {"__type":"com.amazonaws.dynamodb.v20120810#InternalFailure","Message":"The request processing has failed because of an  (truncated...)

**Comment by baopham** [comment]
```
Next exception 'Aws\DynamoDb\Exception\DynamoDbException' with message 'Error executing "CreateTable" on "http://localhost:8000"; AWS HTTP error: cURL error 7: Failed to connect to localhost port 8000: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /var/www/adinton_2/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:159
Stack trace:
```

Did you create your own tables yet?

**Comment by ebisbe** [comment]
Yes I created my own tables. I donwloaded it from amazon and that one is working
