### ISSUE TITLE
passport integration with DynamoDB

### ISSUE THREAD

**Issue by testsoftuvo** [baopham/laravel-dynamodb#151]
Hi , 
I am using library , its working fire without access token integration but when I am gloing to integrate https://laravel.com/docs/5.4/passport , then I am unable to make any miragtion for it . How can I compatible the migration of passport with it?

**Comment by baopham** [comment]
Could you be more specific? e.g. what errors do you see, what are the steps that you performed, what your configs look like, etc. Thanks!

**Comment by foo123** [comment]
Also inrterested in dynamo/passport integration

**Comment by thomasedwards** [comment]
I think this’ll be quite tricky and probably goes outside the scope of just being a DynamoDB provider for Laravel. https://laravel.com/docs/7.x/passport#overriding-default-models provides instructions for making your own models and customising them to suit you. There are too many variables in DynamoDB to suggest how one should go about implementing it.
