### ISSUE TITLE
Support for Laravel 5.7

### ISSUE THREAD

**Issue by lamungu** [baopham/laravel-dynamodb#155]
**Description**

Hi. We are currently upgrading our application to Laravel 5.7. Of the packages affected, laravel dynamo-db is only supporting version up to 5.6.38.

I would like to know if this is in the works, as this may be an issue for other applications using this package and willing to upgrade or integrate in the latest version as well.

**Debug info**

```
- baopham/dynamodb 4.5.0 requires illuminate/database 5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.* || 5.6.* -> satisfiable by laravel/framework[v5.6.38], illuminate/database[v5.1.1, v5.1.13, v5.1.16, (...), v5.6.9].
```

**Version info**

* Laravel: 5.7
* laravel-dynamodb: latest

**Comment by baopham** [comment]
Interesting! Thanks to @jilster. Support for 5.7 was just merged. Could you try laravel-dynamodb@4.9.0?

**Comment by lamungu** [comment]
Worked wonders, Thank you!
