### ISSUE TITLE
auto insert record when run all query

### ISSUE THREAD

**Issue by fadiabualnaser** [baopham/laravel-dynamodb#156]
I use the model the save some data then after that i try to retrieve them using all() function, the records came back with new one, so i think with every time i call all query new record added to my table.

* Laravel: 5.6
* laravel-dynamodb: latest

**Comment by baopham** [comment]
That is really not possible. Can you clarify more? What is your setup? code to reproduce it?

**Comment by zoul0813** [comment]
@baopham looks like he already closed the issue
