### ISSUE TITLE
updating item

### ISSUE THREAD

**Issue by Garine519** [baopham/laravel-dynamodb#161]
I'm trying to update an attribute where its of type 'map'
primary key: op_city_id (sort key)
please see 
https://stackoverflow.com/questions/52715435/how-can-i-update-a-dynamodb-model/52715730#52715730

* Laravel: 5.5
* laravel-dynamodb: latest

**Comment by sahilsharma011** [comment]
You can update the map attribute in the Eloquent Object and then save it to DynamoDB.

```
$dynamo_configuration->info['shopper_logs_enabled'] = '0';
$dynamo_configuration->save();
```

**Comment by Garine519** [comment]
@sahilsharma011 I'm getting an error 

> Indirect modification of overloaded property App\DynamoConfiguration::$info has no effect

**Comment by sahilsharma011** [comment]
Can you show your updated code?

**Comment by sahilsharma011** [comment]
Correct code
```
$dynamo_configuration = DynamoConfiguration::where('op_city_id', 1)->first();
$info = $dynamo_configuration->info;
$info['shopper_logs_enabled'] = '0';
$dynamo_configuration->info = $info;
$dynamo_configuration->save();
return $dynamo_configuration;
```
