### ISSUE TITLE
How to compare created_at date in DB

### ISSUE THREAD

**Issue by testsoftuvo** [baopham/laravel-dynamodb#162]
**Describe the bug**
I want to select the records created today .
-I have write the query but its not working , when I checked in DB created_at stored as string.

- not selecting data for today created records.

**Schema**

Describe your table schema:
* Primary key / composite key
* Any index?
id as primary key.

**Debug info**

Show the query that you're having trouble with by copy-pasting the result of:

```php
print_r($query->toDynamoDbQuery());
```

**Version info**

* Laravel: 5.4
* laravel-dynamodb: latest

**Comment by baopham** [comment]
What is the type of the column `created_at`? What have you tried so far? What is the query?

**Comment by testsoftuvo** [comment]
I haven't saved it separately , as laravel by default consider created and updated dates, I have tried where created_at between 7 days

**Comment by baopham** [comment]
I meant the type you defined in your DynamoDB table. What is it? Is it string?
