### ISSUE TITLE
how to add join query?

### ISSUE THREAD

**Issue by gauravdaxini1995** [baopham/laravel-dynamodb#164]
**Describe the bug**

I have to join two tables agency and users where users table have comman details and other unique details of agency will store in agency table. so i want get all info ageny from both tables using dynamodb so how can get it?

**Schema**

Describe your table schema:
**users** table have id which is unique generate by uuid hash.
**agency** table have id which is unique and user_id is as foreign key. 

**Version info**

* Laravel: 5.5
* laravel-dynamodb: latest

**Comment by baopham** [comment]
The first thing I'd look for is to check if DynamoDB can handle join. And this is the first Google result: https://stackoverflow.com/questions/36753861/how-to-join-tables-in-aws-dynamodb

So short answer is no.

But you can have a work around to first get the ID of the associated record and then do a fetch on that record. Another way is to denormalize the data as the second answer in Stackoverflow explains. 

If you choose to go with the first approach, you could just wrap all this in a custom method in the `Agency` model:

```php
function findUser($agencyId) {
  $agency = $this->find($agencyId, ['user_id']);
  return $agency ? User::find($agency->user_id) : null;
}
```

Hope that helps.
