### ISSUE TITLE
Model Not Saving to DynamoDB When Called From Job in Queue

### ISSUE THREAD

**Issue by dougblackjr** [baopham/laravel-dynamodb#165]
I have a controller that saves an array to a Redis queue, which is then saved to the database. This has worked with no issue to MySQL, but doesn't seem to process from the queue to DynamoDB. It instead saves the queued item to the MySQL DB instead.

If I move the job method for saving the model object directly into the controller, I have no problem saving it to DynamoDB. The issue is only happening when I am saving it in the job.

Model:
```
class Hit extends \BaoPham\DynamoDb\DynamoDbModel
{

	protected $table = 'engauge-hits';

	protected $dates = ['created_at', 'updated_at', 'deleted_at'];

	protected $fillable = ['id', 'url', 'other_data'];

}
```

Controller:
```
public function register(Request $request) {

	$hitToQueue = array(
		'id' => Uuid::generate()->string,
		'url' => $request->url,
		'other_data' => $request->other_data,
	);

	// Test without queue
	RegisterHit::dispatch($hitToQueue)->onQueue('hits');

	return response()->json(['response' => 'registered']);

}
```

Job:
```
<?php

namespace App\Jobs;

use App\Hit;
use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Support\Facades\Redis;
use Log;

class RegisterHit implements ShouldQueue
{
	use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

	protected $hit;

	/**
	 * Create a new job instance.
	 *
	 * @return void
	 */
	public function __construct($hit)
	{
		$this->hit = $hit;
	}

	/**
	 * Execute the job.
	 *
	 * @return void
	 */
	public function handle()
	{

		$hit = new Hit();

		$hit->id = $this->hit['id'];
		$hit->url = $this->hit['url'];
		$hit->other_data = $this->hit['other_data'];

		$hit->save();
		
	}

}
```

Am I missing anything in how this is saved in the queue than it would be otherwise? Appreciate any help you can give!

**Comment by baopham** [comment]
Hmm, that's weird. Can you log what happens in the job handle method? Any exception?
Can you also try and remove SerializesModels trait? (I don't have things setup for testing right now and won't be able to fully look into it until weekend)

**Comment by dougblackjr** [comment]
@baopham Thank you! Unfortunately, there is nothing in the logs, and `SerializesModels` doesn't seem to impact it.

**Comment by baopham** [comment]
So I'm slightly confused by "It instead saves the queued item to the MySQL DB", which MySQL table is it saved to? I think it's just the serialized job item that is saved in MySQL.

Could you turn on dynamodb logging: https://github.com/baopham/laravel-dynamodb/blob/7367d68d686a5eb71b2d25c8968270a92df38622/config/dynamodb.php#L52

Also, could you check if `$hit->save()` returns `true` or `false`?

And see if the request fails?

**Comment by dougblackjr** [comment]
Sorry, I should have clarified.

The process should work as such:
1. The hit gets saved as an array to the Redis queue via the Controller.
2. The queue saves the hit via the Job.

If this is the case, it does not save to DynamoDB.

If I make it so the Controller immediately saves the hit, then it saves just fine. Only when it's getting sent to the Redis queue is it failing.

I have Dynamodb debug on and nothing is being returned. `$hit->save()` returns `true`.

**Comment by dougblackjr** [comment]
I processed the queue manually and found there was a type mismatch in the ID. Got it going. Thank you!
