### ISSUE TITLE
Numbers are created as a string

### ISSUE THREAD

**Issue by joseraul** [baopham/laravel-dynamodb#166]
Hi!

All numbers are created as a string in the database. What makes impossible to order them. Do you have any idea why this could be happening?

Thanks

**Comment by baopham** [comment]
That shouldn't be the case.

Can you share your DynamoDB schema, Eloquent model and the query you made?

**Comment by joseraul** [comment]
Thanks for the quick response!

Eloquent model (nothing special)
```
class Sample extends DynamoDbModel
{
    protected $table = 'strategy_samples';
    protected $guarded = [];
}
```
I don't think the query is much relevant:
```
$queryBuilder = $queryBuilder->where('score', '>=', $filters['score']);`
```
I attach an image of the database, see how the `high` value is ordered as a string
![image](https://i.imgur.com/SfhODM0.png)

The Schema: I didn't "set" the schema anyplace.. it's done "on the fly".. not sure about this point, maybe my issue is here?

**Comment by baopham** [comment]
Are you certain that the values were saved as numbers? I think on DynamoDB UI you can inspect the type.

**Comment by joseraul** [comment]
I didn't find a place to see the schema in the DynamoDB, but I guess are stored as a string.
How can I change? I mean, do I have to do anything special during a `create()` or a `save()`?

**Comment by sahilsharma011** [comment]
You can see the stored schema in dynamodb by clicking on the hash key of each row. Also I think that you need to typecast your input to float before saving into dynamodb using eloquent.

**Comment by joseraul** [comment]
Yep, that worked. I was trying the Eloquent `$cast = []` property, but that didn't seem to work, once I did manually the data is stored correctly. Maybe it is something that could be in the documentation?
Thanks @sahilsharma011 & @baopham !

**Comment by baopham** [comment]
Good point, I need to double check if `$cast` is working properly. Created #167 for tracking.
