### ISSUE TITLE
How to order by any key

### ISSUE THREAD

**Issue by gilbertoalbino** [baopham/laravel-dynamodb#168]
Hi, there.

I am trying to order by "id" but it seems not to work properly.

I tried:

```
$model->orderBy('id', 'desc')->all();
$model->oderByDesc('id')->all()
```

But none seemed to work.

Can you share an example of how to order by id by DESC for this data structure:

```
[{
  "id":1,
  "name":"John Doe"
},{
  "id":2,
  "name":"Mary Doe"
}];
```

Thanks in Advance for great work!

**Comment by baopham** [comment]
Do you have a sort key? I'd recommend you to read up on `ScanIndexForward` first then this would make more sense to you: https://github.com/baopham/laravel-dynamodb#decorate-query

**Comment by gilbertoalbino** [comment]
Thanks, I've created a new package to replace yours!
