### ISSUE TITLE
How to query array of objects using where?

### ISSUE THREAD

**Issue by gilbertoalbino** [baopham/laravel-dynamodb#169]
Hi, there!

How can I query an array of objects using where for this data structure?

```
{
  "logs": [
    {
      "type": "info",
      "message": "some message..."
    },
    {
      "type": "error",
      "message": "some message..."
    },
    {
      "type": "info",
      "message": "some message..."
    }
  ]
}
```

I've tried:

`$model->where('log[0].type', 'info')->get();`

And it worked, of couse:

But how can I get ALL logs inside that array?
Is there any "*" placeholder?

Thanks in Advance!

**Comment by baopham** [comment]
> But how can I get ALL logs inside that array?
> Is there any "*" placeholder?

Sorry, I don't quite get the question. If you can come up with the raw DynamoDB query first, then I could help map it back to Eloquent syntax.

**Comment by gilbertoalbino** [comment]
Thanks, I've created a new package to replace yours!
