### ISSUE TITLE
ClientResolver.php line 335: Missing required client configuration options: where to setup these configration

### ISSUE THREAD

**Issue by naveenksingh** [baopham/laravel-dynamodb#17]

**Comment by baopham** [comment]
Did you set up the settings in `config/services.php`? https://github.com/baopham/laravel-dynamodb/blob/master/README.md will show you how.

**Comment by naveenksingh** [comment]
sorry I didn't set up it previously but after set up it's still giving the same error. I set the configuration to
```
'dynamodb' => [
        'key' => env('abc'),
        'secret' => env('123'),
        'region' => env('us-east-2'),
        'local_endpoint' => env('http://localhost:3000'),
        'local' => env('dont know what to put here so i putted the same value http://localhost:3000'),
    ],

```
and i still getting the same error

**Comment by baopham** [comment]
`env()` is a function to get your environment variable.
In your `.env`, you should have:

```
DYNAMODB_KEY=<insert your AWS access key>
DYNAMODB_SECRET=<insert your AWS secret key>
DYNAMODB_REGION=us-east-2
DYNAMODB_LOCAL_ENDPOINT=http://localhost:3000
DYNAMODB_LOCAL=<true or false - set to true if you want to run against the local dynamodb>
```

and then in your `config/services.php`:

```
'dynamodb' => [
        'key' => env('DYNAMODB_KEY'),
        'secret' => env('DYNAMODB_SECRET'),
        'region' => env('DYNAMODB_REGION'),
        'local_endpoint' => env('DYNAMODB_LOCAL_ENDPOINT')
        'local' => env('DYNAMODB_LOCAL')
    ],
```

**Comment by naveenksingh** [comment]
thanks a lot for the help I think it's set up now. Also I am now experiencing lack of practical knowledge for using dynamodb with laravel I found the codes for using simple php with dynamodb at 

(http://docs.aws.amazon.com/amazondynamodb/latest/gettingstartedguide/GettingStarted.PHP.01.html?shortFooter=true) 

but I cant found any thing like that for use in laravel with models.
I tried something awkward but when i hit the page it loads for a long time and then say maximum execution time exceeded.
my code is
Model `Movies.php`
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use BaoPham\DynamoDb\DynamoDbModel;


class Movies extends DynamoDbModel
{
    //

}
```
controller BasicController.php

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Movies;

class BasicController extends Controller
{
    //

    function firsttest(){
    	$model = new Movies;
    	$model->id = 'de305d54-75b4-431b-adb2-eb6b9e546014';
		$model->save();
    	echo "hello";
    }
}
 

```

error

![fdsf](https://cloud.githubusercontent.com/assets/13255427/14700664/c0f168dc-07be-11e6-98d0-8963a21e2d66.png)

_can you tell me any link where I could find some stuff. or tell me what I am doing wrong._

**Comment by baopham** [comment]
You won't find anywhere that has examples to use DynamoDB with Eloquent because it is not supported by Laravel. This is why I created this package. Check out the examples in the README.

Check the logs, check if you created the DynamoDB table in AWS beforehand, check if you have the hash key set up correctly, etc. There are a lot of possibilities. But check the Laravel logs first.

**Comment by naveenksingh** [comment]
thanks for the help. now its working properly, and one more thing Its working properly when I use the local dynamodb which is installed separately on my machine and also working with the connecting to dynamodb.us-east-1.amazonaws.com. but not working on the copy of dynamodb installed at vendor/baopham/dynamodb/ . Any way at last I have put it online so why not now. Thank You
