### ISSUE TITLE
Auth Login Laravel

### ISSUE THREAD

**Issue by alehempel** [baopham/laravel-dynamodb#170]
Hello everyone,
Can someone help me to use the auth of laravel?
Attached my model controller and error when signing in.
Thank you for any help.

![model](https://user-images.githubusercontent.com/21158903/48033869-46ffe000-e144-11e8-8b78-ded386587b6e.png)
![controller](https://user-images.githubusercontent.com/21158903/48033873-49fad080-e144-11e8-8765-5d313c220313.png)
![error](https://user-images.githubusercontent.com/21158903/48033875-4c5d2a80-e144-11e8-936f-5afce2c372e3.png)

**Comment by alehempel** [comment]
P.S - everything was together but the second part is my controller login.

**Comment by baopham** [comment]
FYI, this library doesn't have integration with Laravel Auth so I won't be able to help you get auth working completely. But if you could narrow down to the queries that are causing you trouble, it'd be great. 

I also recommend checking out AWS cognito as David suggested here: https://github.com/baopham/laravel-dynamodb/issues/153#issuecomment-423751055

**Comment by baopham** [comment]
Good to hear you found a way to make it work for your project. Closing now. Cheers.
