### ISSUE TITLE
Passing array to DynamoDbQueryBuilder::where() adds only first condition

### ISSUE THREAD

**Issue by mlcollins10** [baopham/laravel-dynamodb#181]
**Describe the bug**

Current Behavior:
If an array of conditions are passed to `DynamoDbQueryBuilder::where()`, only the first condition is stored in `DynamoDbQueryBuilder::$wheres`, and thus, the additional conditions are not applied to the query.

Expected:
All conditions in the array are applied to the query.

I've opened a pull request here: https://github.com/baopham/laravel-dynamodb/pull/180

**Version info**
* Laravel: 5.5
* laravel-dynamodb: latest

**Comment by baopham** [comment]
Closing! Thanks for your contribution.
