### ISSUE TITLE
Call to a member function getMarshaler() on null

### ISSUE THREAD

**Issue by pmayet** [baopham/laravel-dynamodb#183]
**Describe the bug**

On element creation, i have this error : 
`Call to a member function getMarshaler() on null`

**Schema**

```
protected $primaryKey = 'Sku';
protected $compositeKey = ['Sku', 'FileKey'];
```

**Debug info**

Show the query that you're having trouble with by copy-pasting the result of:

```php
$model = new \App\Models\Catalog();
```

**Version info**

* Lumen: 5.7
* laravel-dynamodb: latest

**Comment by tapash** [comment]
I also got the same error. any luck?

**Comment by jdrda** [comment]
There are different way to register providers in Lumen. The correct way is to put this to /bootstrap/app.php
`$app->register(BaoPham\DynamoDb\DynamoDbServiceProvider::class);`
(you can see Register Service Providers section in this file)

**Comment by ItsiAdam** [comment]
I solved this by registering DynamoDbServiceProvider before AppServiceProvider.
