### ISSUE TITLE
php 7.2: The each() function is deprecated.

### ISSUE THREAD

**Issue by arjayads** [baopham/laravel-dynamodb#184]
Composite Keys:

**MyModel::find** or **$model->find** throws **The each() function is deprecated.** error on Php 7.2
 

**Version info**

* php: 7.2
* Laravel: 5.2
* laravel-dynamodb: 4.11.2

**Comment by Tamrael** [comment]
Please provide the file and line number where the deprecated function is called.

There is no use of the native php function "each" at all in the code of this repository so this warning shouldn't originate from laravel-dynamodb

**Comment by arjayads** [comment]
No lines given by the compiler.
The code that raises the error is **MyModel::find**

**Comment by Tamrael** [comment]
This is not a bug in laravel-dynamodb.
Laravel 5.2 is not compatible with php 7.2 according to the docs https://laravel.com/docs/5.2#server-requirements

**Comment by arjayads** [comment]
Okay. Our Laravel apps without laravel-dynamodb are running php 7.2

**Comment by baopham** [comment]
Looks like this can be closed now?
