### ISSUE TITLE
No results returned

### ISSUE THREAD

**Issue by julienmru** [baopham/laravel-dynamodb#197]
**Describe the bug**

I am trying to make a query on the primary key (id) of my DynamoDB. The query works through AWS console but returns no result using this library. Is 'id' a reserved column name? What could be wrong?

**Schema**

Describe your table schema:
* Primary key: id
* Composite key: period

**Debug info**

BaoPham\DynamoDb\RawDynamoDbQuery {#940
  +op: "Scan"
  +query: array:4 [
    "TableName" => "socialbump_prod"
    "FilterExpression" => "#id IN (:a1)"
    "ExpressionAttributeNames" => array:1 [
      "#id" => "id"
    ]
    "ExpressionAttributeValues" => array:1 [
      ":a1" => array:1 [
        "S" => "b0d1eb767f4619df41e290b1dc72902c9622586d"
      ]
    ]
  ]
}

**Version info**

* Laravel: 5.7.28
* laravel-dynamodb: 4.12

**Comment by baopham** [comment]
I don't think it's because of the column `id`. What happens if you don't use `IN`? can you try `where('id', 'b0d1eb767f4619df41e290b1dc72902c9622586d')` first?
