### ISSUE TITLE
DyanmoDb Exception

### ISSUE THREAD

**Issue by wilsonnwu** [baopham/laravel-dynamodb#198]
I am trying to move a PHP application using Sqlite to elasticbeanstalk, instead of using sqlite I want to use DynamoDb, I followed the steps.. but I am getting the following error could you please help..

**### _exception 'Aws\DynamoDb\Exception\DynamoDbException' with message 'Error executing "Scan" on "https://dynamodb.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://dynamodb.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"com.amazonaws.dynamodb.v20120810#ResourceNotFoundException","message":"Requested resource not found"}
 ResourceNotFoundException (client): Requested resource not found - {"__type":"com.amazonaws.dynamodb.v20120810#ResourceNotFoundException","message":"Requested resource not found"}'

GuzzleHttp\Exception\ClientException: Client error: `POST https://dynamodb.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"com.amazonaws.dynamodb.v20120810#ResourceNotFoundException","message":"Requested resource not found"}
 in /var/app/current/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:_**

Stack trace:
#0 /var/app/current/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(100): Aws\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\Psr7\Request), Object(Aws\Command), Array)
#1 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(203): Aws\WrappedHttpHandler->Aws\{closure}(Array)
#2 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(174): GuzzleHttp\Promise\Promise::callHandler(2, Array, Array)
#3 /var/app/current/vendor/guzzlehttp/promises/src/RejectedPromise.php(40): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}(Array)
#4 /var/app/current/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}()
#5 /var/app/current/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(98): GuzzleHttp\Promise\TaskQueue->run()
#6 /var/app/current/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(125): GuzzleHttp\Handler\CurlMultiHandler->tick()
#7 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#8 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#9 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#10 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#11 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#12 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#13 /var/app/current/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#14 /var/app/current/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait()
#15 /var/app/current/vendor/aws/aws-sdk-php/src/ResultPaginator.php(127): Aws\AwsClient->execute(Object(Aws\Command))
#16 /var/app/current/vendor/aws/aws-sdk-php/src/functions.php(51): Aws\ResultPaginator->valid()
#17 /var/app/current/vendor/aws/aws-sdk-php/src/functions.php(68): Aws\map(Object(Aws\ResultPaginator), Object(Closure))
#18 /var/app/current/vendor/baopham/dynamodb/src/DynamoDbQueryBuilder.php(719): Aws\flatmap(Object(Aws\ResultPaginator), Object(Closure))
#19 /var/app/current/vendor/baopham/dynamodb/src/DynamoDbQueryBuilder.php(662): BaoPham\DynamoDb\DynamoDbQueryBuilder->getAll(Array, -1, true)
#20 /var/app/current/vendor/baopham/dynamodb/src/DynamoDbQueryBuilder.php(656): BaoPham\DynamoDb\DynamoDbQueryBuilder->all(Array)
#21 /var/app/current/vendor/baopham/dynamodb/src/DynamoDbModel.php(267): BaoPham\DynamoDb\DynamoDbQueryBuilder->get(Array)
#22 /var/app/current/app/Http/Controllers/HealthController.php(13): BaoPham\DynamoDb\DynamoDbModel::all()
#23 [internal function]: App\Http\Controllers\HealthController->index()
#24 /var/app/current/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#25 /var/app/current/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 /var/app/current/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#27 /var/app/current/vendor/illuminate/container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#28 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(373): Illuminate\Container\Container->call(Array, Array)
#29 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(339): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#30 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(313): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\HealthController), 'index', Array)
#31 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(275): Laravel\Lumen\Application->callControllerAction(Array)
#32 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(260): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#33 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(160): Laravel\Lumen\Application->handleFoundRoute(Array)
#34 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(413): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#35 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(166): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#36 /var/app/current/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(107): Laravel\Lumen\Application->dispatch(NULL)
#37 /var/app/current/public/index.php(28): Laravel\Lumen\Application->run()
#38 {main}

**Schema**

Describe your table schema:
* Primary key / composite key
* Any index?

**Debug info**

Show the query that you're having trouble with by copy-pasting the result of:

```php
print_r($query->toDynamoDbQuery());
```

**Version info**

* Laravel: 5.5
* laravel-dynamodb: latest

**Comment by wilsonnwu** [comment]
can someone please help

**Comment by ShanakaNCG** [comment]
I also have some issues and this community not supporting

**Comment by adamtester** [comment]
This means your table doesn't exist, so you need to create a table for each model name (or merge into one)
