### ISSUE TITLE
Feature: Add table prefixes

### ISSUE THREAD

**Issue by jradtilbrook** [baopham/laravel-dynamodb#199]
Since tables in DynamoDB are all "globally" namespaced and since you could have multiple separate apps running that have tables with the same name (in a standard SQL world) I think this package should optionally support prefixing the tables with some value.

The default of letting Eloquent determine the table name by pluralizing the model name works fine for most situations but not like the one above. Also, just changing the `$table` model property doesn't work well if you want to use the ModelTrait to migrate tables from SQL to DynamoDB since both drivers use that property.

Would you be open to adding this feature?

**Comment by baopham** [comment]
Not sure I understand the proposal. Are you asking if we can set the table name dynamically?

**Comment by thomasedwards** [comment]
I don’t think Eloquent has this feature, so I think it would be odd to include it in this package?

In terms of a ‘global’ namespace, my setup for AWS is to have seperate accounts for each environment, all within one master account. That way everything is kept seperate, but goes through one billing system broken down by account. I can then use the same CloudFormation template for each environment, allowing me test changes all the way through. I think this would be a preferably solution for you, for lots of reasons, rather than using prefixed table names.

**Comment by jradtilbrook** [comment]
Eloquent does support this as the `prefix` option in each of the database drivers in `config/database.php`. I'm aware that multiple accounts is a possibility but the overhead for some might make it not worthwhile, as is my case. I mainly want to prefix the tables so that viewing the tables in the AWS console I can easily see which app owns each one, since you could prefix it with the app name or some identifier.

I still think it's worthwhile since it can be optional and does actually do [something eloquent already supports](https://github.com/laravel/laravel/blob/master/config/database.php#L57).

**Comment by baopham** [comment]
So to clarify, this is what you want:

Given this config:

```
'connection_a' => [
  'prefix' => 'foobar_',
]
```

All the tables using `connection_a` will have the prefix of `foobar` (e.g. if table name is "users", then the actual table name when making the request is `foobar_users`), right?

**Comment by jradtilbrook** [comment]
Yes that's correct.  
What do you think?

**Comment by baopham** [comment]
That's easy to do. For now you can override `getTable` method in your model class to get it working. 

If anyone is interested in implementing this feature, please feel free to jump in. I won't have bandwidth to work on this for a while.

**Comment by thomasedwards** [comment]
Ah sorry @jradtilbrook, I understand now. Eloquent doesn’t have this feature, Eloquent is purely Laravel’s ORM ActiveRecord-style access. This config you’re talking about is in Laravel’s database cofiguration (not part of Eloquent models, but implemented higher-up). I was worried you were seeking it at a purely Eloquent-level. @baopham looks like he’s got it!

**Comment by jradtilbrook** [comment]
Oh yeah sorry for that confusion. I'm happy to implement this since I requested it. I mainly wanted to check if a PR would be accepted before I did one. Thanks :tada:
