### ISSUE TITLE
Using same instance of the model

### ISSUE THREAD

**Issue by rsands2801** [baopham/laravel-dynamodb#20]
When we call a query e.g.

```
$count = Analytics::where('columnA', '524352')
                    ->where('columnB', $source)
                    ->where('columnC', '=', $date)
                    ->get();
```

then proceed to call

```
$campaign_sources = Analytics::where('columnA', '524352')->get();
```

the second query fails with an empty array.  If the previous query returned empty results any subsequent calls to Analytics:: will fail with an empty result.  It is not created a new model class,.

If i do this:

```
new Analytics();
$campaign_sources = Analytics::where('columnA', '524352')->get();
```

the above works as I manually triggered a new Analytics before the second query.

**Comment by baopham** [comment]
yeah, there's a bug with static functions right now. In the mean time, try to call `new` to reset the condition for now. I'll look at it in the weekend.

**Comment by rsands2801** [comment]
Ye there seems to be a major problem around the where function that was created, a where is a build up and should always return $this so the next call to a where can keep going

**Comment by baopham** [comment]
It does return `$this`. Chained methods should still work. However, when you do a new query, you should reset the conditions, if not the old conditions still be around.

**Comment by rsands2801** [comment]
A real easy hack...but it is just that a hack is to reset $this->where after it returns a collection of results e.g. line 321 of DynamoDBModel you could call $this->where = null; and that fixes the issue

**Comment by baopham** [comment]
This won't resolve the root issue that I'm trying to solve.

**Comment by rsands2801** [comment]
No problem, it also fails when passing in multiple where conditions for the same column name

**Comment by rsands2801** [comment]
Ye even changing model is enough to completely break this package.  It is definately unstable

**Comment by baopham** [comment]
@rsands2801 can you try branch `query-builder` and see if it fixes the issue?

**Comment by baopham** [comment]
Branch is now merged to `master`
