### ISSUE TITLE
Provided starting key is invalid

### ISSUE THREAD

**Issue by ShanakaNCG** [baopham/laravel-dynamodb#200]
I'm getting an error like this
"message": "Error executing \"Scan\" on \"https://dynamodb.ap-east-1.amazonaws.com\"; AWS HTTP error: Client error: `POST https://dynamodb.ap-east-1.amazonaws.com` resulted in a `400 Bad Request` response:\n{\"__type\":\"com.amazon.coral.validate#ValidationException\",\"message\":\"The provided starting key is invalid: The provided  (truncated...)\n ValidationException (client): The provided starting key is invalid: The provided key element does not match the schema - {\"__type\":\"com.amazon.coral.validate#ValidationException\",\"message\":\"The provided starting key is invalid: The provided key element does not match the schema\"}",

what I was going to do it pagination for my project. So I used the query 
$query = $model->where('count', 10)->limit(2);
$items = $query->all();
$last = $items->last();
 as your documentation mentioned. 
so these three are working fine and
$items->lastKey()
$last->getKeys()
also working find and provide the last key (my primaryKey). And I have defined the model primarykey also. But when I execute any query from theese thre, I'm getting an error like I mentioned in top. Please help me soluve this. I need this pagination to get it work
$nextPage = $query->after($last)->limit(2)->all();
// or
$nextPage = $query->afterKey($items->lastKey())->limit(2)->all();
// or (for query without index condition only)
$nextPage = $query->afterKey($last->getKeys())->limit(2)->all();

**Comment by baopham** [comment]
can you show us your table schema and how you define the model class?

**Comment by Alok77** [comment]
i have same issue ,can you suggest me if any solution is there

**Comment by thomasedwards** [comment]
afterKey needs the key as an array

     $nextPage = $query
        ->afterKey(['id' => $items->lastKey()])
        ->limit(2)
        ->all();
