### ISSUE TITLE
Not able to query the table

### ISSUE THREAD

**Issue by robbietorinit** [baopham/laravel-dynamodb#204]
**Describe the bug**

Trying to get chats between two people. but fails to do so as it says does not match the schema.

**Schema**

Describe your table schema:
   `protected $primaryKey = 'id';
    protected $table = "chats";
    protected $compositeKey = ['sender_id', 'receiver_id'];`

**Debug info**

Show the query that you're having trouble with by copy-pasting the result of:
$chat = Chats::where([['sender', '1'],['receiver', '2']])->orWhere([['sender', '2'],['receiver', '1']])->get();

**Version info**

* Laravel: 5.8
* laravel-dynamodb: latest

**Comment by robbietorinit** [comment]
Error executing Scan on https://dynamodb.us-west-2.amazonaws.com AWS HTTP error: Client error: `POST https://dynamodb.us-west-2.amazonaws.com` resulted in a `400 Bad Request

**Comment by thomasedwards** [comment]
What is being sent?

Use https://github.com/baopham/laravel-dynamodb#tosql-style to get the raw query.
