### ISSUE TITLE
dynamodb chunk is not working, always return []

### ISSUE THREAD

**Issue by Alok77** [baopham/laravel-dynamodb#205]
i have an model  App\DyanamoDBModalTest();

when in controller i trying to do chunk its not getting data its just return [];

$data = new App\DyanamoDBModalTest();
return $data->chunk(3, function($sd){
foreach($sd as $sd){

}
});

help from anyone is appreciated, thanks.

**Comment by thomasedwards** [comment]
That code doesn’t suggest that it returns `[]`. You’ve named `$sd` twice, which’ll cause confusion or an error.
