### ISSUE TITLE
Comparison Operators

### ISSUE THREAD

**Issue by dhahn** [baopham/laravel-dynamodb#21]
I was wondering is there was way to use the comparison operators that aren't mapped in this package. 

For instance here is a list of the DynamoDb operators:

```
EQ | NE | LE | LT | GE | GT | NOT_NULL | NULL | CONTAINS | NOT_CONTAINS | BEGINS_WITH | IN | BETWEEN
```

I'd like to say `Message::where('key', 'BEGINS_WITH', 'val')`

**Comment by baopham** [comment]
Great idea. I will take a look at it.

**Comment by baopham** [comment]
Pushed to master. Need to add `whereNull` and `whereNotNull`, `orWhereNull`, `orWhereNotNull`. I'll do that later
