### ISSUE TITLE
PHP 7.4 E_NOTICE Bug in Analyzer.hasValidQueryOperator

### ISSUE THREAD

**Issue by paul-automox** [baopham/laravel-dynamodb#211]
**Describe the bug**

We are testing an upgrade to PHP 7.4 and we are getting a bug with the following stack trace:

```    +exception: ErrorException {#1338
      #message: "Trying to access array offset on value of type null"
      #code: 0
      #file: "./vendor/baopham/dynamodb/src/ConditionAnalyzer/Analyzer.php"
      #line: 209
      #severity: E_NOTICE
      trace: {
        ./vendor/baopham/dynamodb/src/ConditionAnalyzer/Analyzer.php:209 { …}
        ./vendor/baopham/dynamodb/src/ConditionAnalyzer/Analyzer.php:116 { …}
        ./vendor/baopham/dynamodb/src/ConditionAnalyzer/Analyzer.php:69 { …}
        ./vendor/baopham/dynamodb/src/DynamoDbQueryBuilder.php:692 { …}
        ./vendor/baopham/dynamodb/src/DynamoDbQueryBuilder.php:662 { …}
        ./vendor/baopham/dynamodb/src/DynamoDbQueryBuilder.php:656 { …}
        ./vendor/automox/landmine/src/legacy/Helpers/CommandLogHelper.php:37 { …}
```
Our CommandLogHelper code is this:

```
        return (bool) $builder
            ->get(array_keys($log->getAttributes()))
            ->filter(function (CommandLog $log) use ($sinceExecTime) {
                return $log->exec_time->greaterThanOrEqualTo($sinceExecTime);
            })
            ->count();
```
I did a dump in hasValidQueryOperator when `$rangeCondition['type']` is empty.  $hash is 'server_id' and $range is 'id'.   Our model key names are id and server_id.  So, a bit confused.

```php
print_r($query->toDynamoDbQuery());
```

**Version info**

* Laravel: 5.5
* laravel-dynamodb: latest

**Comment by YoshiMannaert** [comment]
I'm getting the same bug on our platform. I'm the only one using PHP 7.4, my colleagues are on 7.2 and have no issues

### Version info
- Laravel 5.8.37
- dynamodb: "^5.0"
- PHP 7.4.0

**Comment by baopham** [comment]
@rennokki @JackPriceBurns @thomasedwards would you mind taking a look at this issue?

**Comment by thomasedwards** [comment]
We’re mostly still on 7.2 here but my home computer is on 7.4 so will give it a whirl!

**Comment by JackPriceBurns** [comment]
This was fixed :)

https://github.com/baopham/laravel-dynamodb/pull/217
