### ISSUE TITLE
How to define KeyConditionExpression instead of FilterExpression in model query?

### ISSUE THREAD

**Issue by wattsie** [baopham/laravel-dynamodb#219]
Hi All,
  I hope everyone is safe and well during these interesting and challenging times.

  Just wondering if someone would kindly offer some pointers, if I am doing something wrong please let me know.

  This could be similar or related to #185 

**Details and Debug info**
  I have a simple DynamoDB table 'myTable' with three (3) columns, 'myid' is a 'Primary partition key', 'mytime' is a 'Primary sort key' and 'data' has all other data.

  I setup a model 'MyModel':
```php
class MyModel extends DynamoDbModel
{
    protected $table = 'myTable'; 
    protected $guarded = [];
    protected $primaryKey = ['myid'];
}
```
Then created a basic Laravel command to run the following tests.
```php
$model = new MyModel();
```
Run a query.
```php
$query = $model
  ->newQuery()
  ->where('myid', 'IdToMatch')
  ->where('mytime', 'between', ['aStartTime', 'aEndTime'])
;
$raw = $query->toDynamoDbQuery();
dump($raw->op);
dump($raw->query);
```
Outputs
```php
"Scan"
array:4 [
  "TableName" => "myTable"
  "FilterExpression" => "#myid = :a1 AND (#mytime BETWEEN :a2 AND :a3)"
  "ExpressionAttributeNames" => array:2 [
    "#myid" => "myid"
    "#mytime" => "mytime"
  ]
  "ExpressionAttributeValues" => array:3 [
    ":a1" => array:1 [
      "S" => "IdToMatch"
    ]
    ":a2" => array:1 [
      "S" => "aStartTime"
    ]
    ":a3" => array:1 [
      "S" => "aEndTime"
    ]
  ]
]
```
I get the expect array, however a 'Scan' was used.

**Describe the bug**
So, I tried to decorate it to use 'Query'
```php
->decorate(function (RawDynamoDbQuery $raw) {
  $raw->op = 'Query';
})
```
Outputs:
```php
"Query"
array:4 [
  "TableName" => "myTable"
  "FilterExpression" => "#myid = :a1 AND (#mytime BETWEEN :a2 AND :a3)"
  "ExpressionAttributeNames" => array:2 [
    "#myid" => "myid"
    "#mytime" => "mytime"
  ]
  "ExpressionAttributeValues" => array:3 [
    ":a1" => array:1 [
      "S" => "IdToMatch"
    ]
    ":a2" => array:1 [
      "S" => "aStartTime"
    ]
    ":a3" => array:1 [
      "S" => "aEndTime"
    ]
  ]
]

Error executing "Query" on "https://..."; AWS HTTP error: Client error: `POST https://...` resulted in a `400 Bad Request` response:
{"__type":"com.amazon.coral.validate#ValidationException","message":"Either the KeyConditions or KeyConditionExpression  (truncated...)
 ValidationException (client): Either the KeyConditions or KeyConditionExpression parameter must be specified in the request. - 
 {"__type":"com.amazon.coral.validate#ValidationException","message":"Either the KeyConditions or KeyConditionExpression parameter must be specified in the request."}
```

The issue appears to be that a 'FilterExpression' has been used instead of a 'KeyConditionExpression' 

For example, if I manually force back to 'KeyConditionExpression':
```php
$query = $model
  ->newQuery()
  ->decorate(static function (RawDynamoDbQuery $raw) {
    $raw->op = 'Query';
    $raw->query['KeyConditionExpression'] = '#myid = :a1 AND (#mytime BETWEEN :a2 AND :a3)';
    unset($raw->query['FilterExpression']);
  })
  ->where('myid', 'IdToMatch')
  ->where('mytime', 'between', ['aStartTime', 'aEndTime'])
;
$raw = $query->toDynamoDbQuery();
dump($raw->op);
dump($raw->query);
```
Outputs:
```php
"Query"
array:4 [
  "TableName" => "myTable"
  "ExpressionAttributeNames" => array:2 [
    "#myid" => "myid"
    "#mytime" => "mytime"
  ]
  "ExpressionAttributeValues" => array:3 [
    ":a1" => array:1 [
      "S" => "IdToMatch"
    ]
    ":a2" => array:1 [
      "S" => "aStartTime"
    ]
    ":a3" => array:1 [
      "S" => "aEndTime"
    ]
  ]
  "KeyConditionExpression" => "#myid = :a1 AND (#mytime BETWEEN :a2 AND :a3)"
]
```
And I get the expected output....

Any pointers.

PS: For the time being, I am moving away from the model and calling Query Builder directly:
```php
$results = DynamoDb::table('myTable')
  ->setKeyConditionExpression('#myid = :myid AND (#myts BETWEEN :s AND :e)')
  ->setExpressionAttributeName('#myid', 'myid')
  ->setExpressionAttributeName('#myts', 'myts')
  ->setExpressionAttributeValue(':myid', DynamoDb::marshalValue('IdToMatch'))
  ->setExpressionAttributeValue(':s', DynamoDb::marshalValue('aStartTime'))
  ->setExpressionAttributeValue(':e', DynamoDb::marshalValue('aEndTime'))
  ->prepare()->query();
``` 

**Version info**
```php
"require": {
  "php": "^7.2.5",
  "baopham/dynamodb": "^7.0",
  "guzzlehttp/guzzle": "^6.5.2",
  "laravel/framework": "^7.4.0",
}
```

**Comment by thomasedwards** [comment]
Have you tried using an index?

    protected $dynamoDbIndexKeys = [
        'mytime_index' => [
            'hash' => 'myid',
            'range' => 'mytime'
        ],
    ];

then use

    ->withIndex('mytime_index')

in your query?

**Comment by wattsie** [comment]
HI Thomas,
  Thanks for the reply.

  Still a little unclear, are you suggesting setup an index using "create index" on DynamoDB table with partition key of 'myid'? Should it also have a sort key?

  I tried creating an index, "mytime-index" with the primary key of mytime no sort key, then added the "$dynamoDbIndexKeys" to the model and tried
```
$query = $model
            ->newQuery()
            ->withIndex('mytime-index')
            ->where('myid', $anId)
            ->where('mytime', 'between', [$startTime, $endTime])
        ;
```
It responded with
```
Query key condition not supported
```

Or if I try
```
$res = MyModel::where('myid', $anId)-get();
// responds with
The provided key element does not match the schema
```

Thanks for your assistance.

Cheers.

**Comment by wattsie** [comment]
Thanks again @thomasedwards 

So I am at a loss.. guess I am going crazy ;-)

If I use this, I can easily get the expected results.
```
$res = DynamoDb::table($myTableName)
  ->setIndexName('myid')
  ->setKeyConditionExpression('#myid = :myid AND (#mytime BETWEEN :beg AND :end)')
  ->setExpressionAttributeName('#myid', 'myid')
  ->setExpressionAttributeName('#mytime', 'mytime')
  ->setExpressionAttributeValue(':myid', DynamoDb::marshalValue($thisID))
  ->setExpressionAttributeValue(':beg', DynamoDb::marshalValue($startTime))
  ->setExpressionAttributeValue(':end', DynamoDb::marshalValue($endTime))
;
```
I just cannot work out how to get the model working to match this.

Any suggestions would be muchly appreciated.

Cheers.

**Comment by thomasedwards** [comment]
My understanding is that whenever you use a `where` it’ll revert to a scan, unless you have setup those wheres as being keys in an index in your model:

```
protected $dynamoDbIndexKeys = [
    'mytime_index' => [
        'hash' => 'myid',
        'range' => 'mytime'
    ],
];
```

If you have a sort, yes you should include it there too. This package assumes you mean scan unless you’re looking for specific items in your index.

However, looking at the complexity of your query, I think you’re best off just using that and putting it in your model for easy access!

**Comment by wattsie** [comment]
Thanks again @thomasedwards 

So not sure if I missed this somewhere in the docs, but it so working.

I simply added the following to the model:
```
protected $compositeKey = ['myid', 'mytime'];
```

Thanks for your assistance.

Now all I need to do is work out how to convert the timestamp in MS to a date.
Looks like Carbon is using 'Carbon::createFromTimestamp()' when it should use 'Carbon::createFromTimestampMS()'

Again, many thanks.

Cheers.

**Comment by thomasedwards** [comment]
Ahh! That simple! 😄

Good luck with your dates
