### ISSUE TITLE
Question: Can you query a dynamodb map (json) column?

### ISSUE THREAD

**Issue by voicingewe** [baopham/laravel-dynamodb#222]
Example:
Item{
id
time
meta: {
somedata: a,
someotherdata: b,
someotherdata: c
}
}

**Comment by thomasedwards** [comment]
You can only scan the contents, not query the field, or read as an object. Anything that you need to query should be a secondary index. If you find that you need to query a lot of different data, then DyanmoDB may not be the right tool for the job, or you could also copy some data in Elasticsearch, which allows for advanced querying.

**Comment by voicingewe** [comment]
@thomasedwards Sorry I am not in charge of the schema of the dynamodb database. I was just looking to see if there was a way with this tool to be able to query the map type found in DynamoDB. The data in in dynamo is currently in the form

```
Item {
   String: hash (Primary Key)
   String: time
   Map: meta: {
              String field1: a,
              String field2: b,
              String field3: c
    }
}
```

I was only wondering if I could use laravel-dynamodb to query or scan to find an item with a corresponding meta.field1 value.

I am not in the position to dictate changing an enterprise system to add elastic search or some middle temporary database to query from.

**Comment by voicingewe** [comment]
I am going to assume there isnt but if there is please comment

**Comment by thomasedwards** [comment]
Ah yeah sorry, not really the way DynamoDB works I’m afraid! Hope you can find a solution.
