### ISSUE TITLE
Create table with migration

### ISSUE THREAD

**Issue by Easy987** [baopham/laravel-dynamodb#224]
Hello,
I need to create tables with laravel migrations. .Can i achieve this?
Thanks

**Comment by thomasedwards** [comment]
Dynamo doesn’t need migrations as the structure reacts to the data given, so there’s no set structure beyond things like the key.

But, if you want to keep track of the creation of tables and keys (which is a great idea), use the [PHP SDK for CloudFormation](https://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-cloudformation.html) to run CloudFormation.
