### ISSUE TITLE
Getting Error executing "Scan", AWS HTTP error: Client error resulted in a `400 Bad Request`

### ISSUE THREAD

**Issue by xantoshlamsal** [baopham/laravel-dynamodb#228]
I am able to fetch data from dynamodb(aws) when working locally, but when code is deployed, there is following response:

Error executing "Scan" on "https://dynamodb.ap-southeast-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://dynamodb.ap-southeast-1.amazonaws.com` resulted in a `400 Bad Request` response: {"__type":"com.amazon.coral.service#UnrecognizedClientException","message":"The security token included in the request i (truncated...) UnrecognizedClientException (client): The security token included in the request is invalid - {"__type":"com.amazon.coral.service#UnrecognizedClientException","message":"The security token included in the request is invalid"}

Security tokens are valid. 
Working fine with this url(local) : http://127.0.0.1:8000/api/comm
Getting above response after deployed: https://yvgk07laef.execute-api.ap-southeast-1.amazonaws.com/dev/api/comm

Table looks like this:
{
    "communication_medium ": "phone",
    "customer_id": "asdf asdf asdfas dflkag ",
    "details": "asdfa dflaksdf asfasdf sd",
    "order_id": "asdf asdf asdfasdf as",
    "id": "asdfsdaf"
  }

* Laravel: 5.5
* laravel-dynamodb: latest

**Comment by thomasedwards** [comment]
They key part of this is the `The security token included in the request is invalid` error. Have you got that all setup correctly on the server? Correct variables and env config?

**Comment by xantoshlamsal** [comment]
Thank you, it is working fine now. After I removed AWS_SESSION_TOKEN line in app=>dynamodb.php.
