### ISSUE TITLE
An example of DynamoDB

### ISSUE THREAD

**Issue by qyqyqy03** [baopham/laravel-dynamodb#23]
hi, i am a new laravel and aws user
i had finished the steps before [Usages] in documentation
but i cant understand how to use it
Can anyone give an example of what code should apply and where?

Thanks!

**Comment by baopham** [comment]
Hello, thanks for reminding me to update the docs. Here are the steps:

1. Configure your dynamodb credentials in `config/services.php`
1. Create your model class as usual
1. Extend this class with `BaoPham\DynamoDb\DynamoDbModel`
1. Set your `$fillable` property
1. Use the Eloquent syntax as usual

**Comment by qyqyqy03** [comment]
hi, thanks for your reply
but I still have difficult to connect dynamodb

Do i correct below for the model class?
app/Product.php
`<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class Product extends BaoPham\DynamoDb\DynamoDbModel
{
}
`

app/Http/Controllers/ProductController.php
`<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Product;
class ProductController extends Controller
{
    public function index()
    {
    	$products = Product::all();    	
    	return view('products.index')->with('products', $products);
    }
}
`

such as I have a "products" table
- id
- name
but here have some errors

**Comment by baopham** [comment]
what are the errors?

**Comment by qyqyqy03** [comment]
FatalErrorException in Product.php line 8:
Class 'App\BaoPham\DynamoDb\DynamoDbModel' not found

**Comment by baopham** [comment]
You have the namespace wrong, put `\` in front of `BaoPham`

```
class Product extends \BaoPham\DynamoDb\DynamoDbModel
```

If you use an IDE (PhpStorm), it'd help with error like this.

**Comment by qyqyqy03** [comment]
InvalidArgumentException in ClientResolver.php line 350:
Missing required client configuration options:

**Comment by qyqyqy03** [comment]
at ClientResolver->throwRequired(array('credentials' => array('key' => null, 'secret' => null), 'region' => null, 'version' => '2012-08-10', 'service' => 'dynamodb', 'exception_class' => 'Aws\DynamoDb\Exception\DynamoDbException', 'config' => array(), 'scheme' => 'https')) in ClientResolver.php line 246


but I have already added the code in services.php

> 'dynamodb' => [
>         'key' => env('AKIAJ......'),
>         'secret' => env('X3kSNAEjxCST......'),
>         'region' => env('US_EAST_1'),
>         'local_endpoint' => env('DYNAMODB_LOCAL_ENDPOINT'), 
>         'local' => env('DYNAMODB_LOCAL'), 
>     ],

Thanks!

**Comment by qyqyqy03** [comment]
DynamoDbException in WrappedHttpHandler.php line 192:
Error executing "Scan" on "https://dynamodb.us_east_1.amazonaws.com"; AWS HTTP error: cURL error 6: Could not resolve host: dynamodb.us_east_1.amazonaws.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

some errors

**Comment by baopham** [comment]
Please check your `services.php` again and see if you have put all the correct info. Good way to check also is to use `artisan tink` and call `config('services.dynamodb')`

**Comment by qyqyqy03** [comment]
services.php
```
    'dynamodb' => [
        'key' => env('DYNAMODB_KEY'),
        'secret' => env('DYNAMODB_SECRET'),
        'region' => env('DYNAMODB_REGION'),
        'local_endpoint' => env('DYNAMODB_LOCAL_ENDPOINT'), // see http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.DynamoDBLocal.html
        'local' => env('DYNAMODB_LOCAL'), // true or false? should use dynamodb_local or not?
    ],
```

and i added the code in .env
```
DYNAMODB_KEY=XXX...
DYNAMODB_SECRET=XXX...
DYNAMODB_REGION=US_EAST_1
```

and the checking result
is
=> [
     "key" => "XXX...",
     "secret" => "XXX...",

     "region" => "US_EAST_1",
     "local_endpoint" => null,
     "local" => null,
   ]
>>>

**Comment by baopham** [comment]
Change to `us-east-1` for the region

**Comment by qyqyqy03** [comment]
error is the same
... "https://dynamodb.us-east-1.amazonaws.com" ...
only us_east_1 to us-east-1 changed

**Comment by baopham** [comment]
are you certain that it is the correct region?

**Comment by qyqyqy03** [comment]
yes, i am using "US East (N. Virginia)" which displayed in the top-right corner
and it works with the no framework php:
'region' => Aws\Common\Enum\Region::US_EAST_1,

**Comment by qyqyqy03** [comment]
Or is that is a feasible way to give me a template repository which just let me to fill in the KEY and SECRET and table name? Then i can connect with dynamodb and display the items on my table.

**Comment by baopham** [comment]
It seems more like a network issue actually.

Why don't you put up a quick repo of what you have so far and I can take a look.

**Comment by qyqyqy03** [comment]
It is a good idea!
https://drive.google.com/open?id=0B7a_eGs6V1ToaHFyX0VYMVRHU00
The project I use "products" as my testing
Thanks!

**Comment by baopham** [comment]
I will take a look in the weekend.

**Comment by qyqyqy03** [comment]
Thank you!

**Comment by baopham** [comment]
I created a table `products` under region `us-east-1` and it's working fine for me. Check your network if somehow it is blocked.

**Comment by qyqyqy03** [comment]
hi
I just added my key and secret in .env
then have a table called "products" like this
https://drive.google.com/file/d/0B7a_eGs6V1TobVdtMFZjNnl0XzQ/view?usp=sharing
with itemid and itemAddress attribute
However, I still got the error of 

> "Error executing "Scan" on "https://dynamodb.us-east-1.amazonaws.com"; AWS HTTP error: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"

**Comment by baopham** [comment]
That sounds more like a different problem. Google will help. For example, http://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate

By the way,
Is `itemid` your primary key? if so, please set it in your `Product` class:

```
protected $primaryKey = 'itemid';
```

by default your primary key is `id`

**Comment by qyqyqy03** [comment]
am i right?
https://drive.google.com/open?id=0B7a_eGs6V1ToUjhUZEdkZEdnTzg

**Comment by baopham** [comment]
Yes, but you should use string for primary key. Dynamodb does not support incrementing ID. You have to set the ID yourself. But this is a separate thing I wanted to point out. You should google for the error that you're getting

**Comment by qyqyqy03** [comment]
thanks!
why you are working fine but I cant for the same repo with same changes?

**Comment by baopham** [comment]
My local server has ssl cert setup correctly?

**Comment by qyqyqy03** [comment]
how to setup?
can I not to use ssl?

**Comment by baopham** [comment]
great

**Comment by qyqyqy03** [comment]
hi
I have a problem with upload photo with S3

In the ..blade.php
`{!!Form::file('image')!!}`

In the Controller
```
public function store(Request $request)
    {
...
$imageFileName = "123.png";
$s3 = \Storage::disk('s3');
        $filePath = '/mybucket/' . $imageFileName;
        $s3->put($filePath, file_get_contents($request->file('image')), 'public');
}
```

Why I have an error on

> file_get_contents(): Filename cannot be empty

**Comment by baopham** [comment]
This has nothing to do with this library. Please use Stackoverflow for this.
