### ISSUE TITLE
Unable to get records as per sort_key

### ISSUE THREAD

**Issue by connect-javed001** [baopham/laravel-dynamodb#235]
Trying to get records in descending order, but it's always returns same result, I have sort_key (as current timestamp), can u please help me ?

Also provide solution when we want to search records based on date filter using sort key

**Comment by thomasedwards** [comment]
What code are you using? Have you delcared the index in your model?

**Comment by connect-javed001** [comment]
No, Defined primaryKey & compositeKey only

**Comment by thomasedwards** [comment]
Can you show us your model?

**Comment by connect-javed001** [comment]
<?php
namespace App\Models;

use BaoPham\DynamoDb\DynamoDbModel;

class Activity extends DynamoDbModel
{
    protected $table;
    protected $primaryKey;
    protected $compositeKey;

    public function __construct()
    {
        $this->primaryKey = config('dynamodb.connections.aws.hash_key');
        $this->compositeKey = [
            config('dynamodb.connections.aws.hash_key'),
            config('dynamodb.connections.aws.sort_key')
        ];
        $this->table = "Activity";
    }
}

**Comment by thomasedwards** [comment]
Could you try using the index?

    /**
     * Indexes.
     * [
     *     '<simple_index_name>' => [
     *          'hash' => '<index_key>'
     *     ],
     *     '<composite_index_name>' => [
     *          'hash' => '<index_hash_key>',
     *          'range' => '<index_range_key>'
     *     ],
     * ]
     *
     * @var array
     */
    protected $dynamoDbIndexKeys = [
        'count_index' => [
            'hash' => 'count'
        ],
    ];

**Comment by connect-javed001** [comment]
where we need to define above index ?

**Comment by thomasedwards** [comment]
In the model?

**Comment by connect-javed001** [comment]
Yes

**Comment by thomasedwards** [comment]
Did it work?

**Comment by connect-javed001** [comment]
No. Still getting same issue

**Comment by thomasedwards** [comment]
What does your model look like now?

**Comment by connect-javed001** [comment]
<?php
namespace App\Models;

use BaoPham\DynamoDb\DynamoDbModel;

class ActivityTracking extends DynamoDbModel
{
    protected $table;
    protected $primaryKey;
    protected $compositeKey;

    /**
     * Indexes.
     * [
     *     '<simple_index_name>' => [
     *          'hash' => '<index_key>'
     *     ],
     *     '<composite_index_name>' => [
     *          'hash' => '<index_hash_key>',
     *          'range' => '<index_range_key>'
     *     ],
     * ]
     *
     * @var array
     */
    protected $dynamoDbIndexKeys = [
        'count_index' => [
            'hash' => 'count'
        ],
    ];

    public function __construct()
    {
        $this->primaryKey = config('aws.hash_key');
        $this->compositeKey = [
            config('aws.hash_key'),
            config('aws.sort_key')
        ];
        $this->table = "ActivityTracking";
    }
}

**Comment by thomasedwards** [comment]
Are you using `withIndex('count_index')` ?

**Comment by connect-javed001** [comment]
Yes

**Comment by connect-javed001** [comment]
Is it compulsory to create index for sorting ?

**Comment by thomasedwards** [comment]
You’ll need to create the index before you can use it.
