### ISSUE TITLE
Question about dynamodb.php config file

### ISSUE THREAD

**Issue by Dumk0** [baopham/laravel-dynamodb#239]
There is *aws_iam_role* block In the project config sample. What for it is? 

Another thing I have faced, is that 'debug' takes much more memory and may cause Memory Limit Error on local dynamodb instance. Maybe this option should also be depending on DYNAMODB_DEBUG env var?

**Comment by JackPriceBurns** [comment]
If you've got an instance role associated with the EC2 instance, you can remove the access key, secret and token from the `dynamodb.php` file the AWS SDK is smart enough to grab this information for you.

You can grab this information manually through the instance metadata api, however I would not recommend doing this.
You can read more here https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html
