### ISSUE TITLE
Table Relationship

### ISSUE THREAD

**Issue by qyqyqy03** [baopham/laravel-dynamodb#24]
Hello, I have an question
I want to display all posts in a page

Here is my dynamodb

> users Table: user_id | name | password
> posts Table: id | body | user_id

user_id for me to link, so one user has many posts
I just simply use **Auth::user()->user_id** to get user id and **request body** to create a new post item

but how to foreach the following?

> name(from users) : body(from posts)

**Comment by baopham** [comment]
You can just do:

```php
foreach ($users as $user) {
   $posts = Post::where('user_id', $user->user_id)->get();
}
```

**Comment by qyqyqy03** [comment]
Yes Thank you so much, it got the data
I used    ` {{ $users = App\User::where('user_id', $post->user_id)->get() }} `   in foreach in blade.php
and it show

> [{"user_id":"123","email":"123@com","password":"1234","first_name":"Tony"}]

but how to get "Tony"?
$users.....[]??

**Comment by baopham** [comment]
Just do `$user = App\User::find($post->user_id)` - you will get the one user record.

Closing since this question actually has nothing to do with this library. I suggest you reading up on Laravel Eloquent docs first.

**Comment by qyqyqy03** [comment]
and now I got this

> {"user_id":"123","email":"123@com","password":"1234","first_name":"Tony"}
how can I get the first_name -- "Tony"?

**Comment by baopham** [comment]
`$user->first_name`

**Comment by qyqyqy03** [comment]
But it hv an error

> Trying to get property of non-object

**Comment by baopham** [comment]
Try to debug by looking at the variable type. Sorry I can't help much on this as it has nothing to do with the library
