### ISSUE TITLE
Combination of wherIn() and update() not working

### ISSUE THREAD

**Issue by mcyncierto** [baopham/laravel-dynamodb#247]
**Describe the bug**

Hi guys, good day! I've tried using the combination of wherIn() and update() function but it doesn't work. Am I missing something? Thanks!

**Debug info**

Sample code:

```php
$query = MyModel::whereIn('id', $ids);
$query->update(['group_name' => $groupName]);
```

**Version info**

* Laravel: 8
* laravel-dynamodb: latest

**Comment by zoe-edwards** [comment]
Sorry, whereIn is very tricky to do because of the way Dynamo indexes.
