### ISSUE TITLE
Issue using Nested attributes

### ISSUE THREAD

**Issue by InderjeetTutor** [baopham/laravel-dynamodb#250]
Hi

I am using baopham/dynamodb package for dynamodb purposes. It's working fine but when I need to filter the query on the behalf of nested attributes. It's not working on my side. 

I want to put the condition into the nested grade column inside the expertise column but I m not able to use expertise.grade attribute in the query so kindly help me. To resolve this issue. 

I also attached the below link. kindly check it once.
https://www.awesomescreenshot.com/image/16346773?key=809483677d9e1e0656c6b66b39db3451

// Nested attributes
$model->where('expertise.grade ', 'bar')->get(); not working.

As per this package, you told us we can able to use nested attributes so kindly look it.

**Comment by thomasedwards** [comment]
The screenshot isn’t working for me, so possibly consider uploading it using the GitHub provided completely free and easy to use upload button.

At the moment I can’t see any issues as you haven‘t provided any code, so I’ll close this for now but if you’re able to provide more detail we can re-open it.
