### ISSUE TITLE
Could I use AssumeRole with baopham dynamodb?

### ISSUE THREAD

**Issue by sinzo33** [baopham/laravel-dynamodb#252]
I'm sorry for my poor English.

I want to use Aws AssumeRole with baopham dynamodb.
Currently there is no such setting on the config/dynamodb.php.
Will I be able to do it in the future?

>Assuming an IAM Role in Another AWS Account
https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_assume_role.html#assuming-an-iam-role-in-another-aws-account

**Comment by JackPriceBurns** [comment]
Unfortunately we don't have this capability, you would need to create an IAM user in the correct AWS account and create access credentials for that user

**Comment by sinzo33** [comment]
Thank you for your reply.
I understand.
