### ISSUE TITLE
Pagination 

### ISSUE THREAD

**Issue by raflyrenaldy** [baopham/laravel-dynamodb#258]
i've seen this documenation https://github.com/baopham/laravel-dynamodb#pagination

but still didnt have solutions. im try to order->limit(4); 
sometimes thats orders does not output data at all. its still bugs ?

**Comment by zoe-edwards** [comment]
You’re not being very clear here, what code are you using? What are you ordering and limiting?

**Comment by raflyrenaldy** [comment]
> You’re not being very clear here, what code are you using? What are you ordering and limiting?

im using lumen 9.x, im just limiting the data from db dynamodb..

**Comment by zoe-edwards** [comment]
Can you show just a the bit of code that’s causing the issue?
