### ISSUE TITLE
Unable to update data using where()

### ISSUE THREAD

**Issue by Geet2312** [baopham/laravel-dynamodb#262]
I'm unable to update data using the eloquent model, this is how I implement 

` TestModel::where(['pk'=>'1','sk'=>'2'])
                    ->update(['first_name'=>'Lai','last_name'=>'James']);`

but if I add first() it updated and I'm not sure whether it is the best practice or not 

` TestModel::where(['pk'=>'1','sk'=>'2'])
                    ->first()
                    ->update(['first_name'=>'Lai','last_name'=>'James']);`

**Comment by zoe-edwards** [comment]
The way DynamoDB works is that you can only update one item at a time, so an update all isn’t really possible. Hence this package does not support that type of query.

**Comment by Geet2312** [comment]
Hi, I'm using a composite key, can you give me an example of how to update data using the model? I am asking this because I fail to update the data following the documentation.

**Comment by zoe-edwards** [comment]
Did you follow the instructions for [Composite Keys](https://github.com/baopham/laravel-dynamodb#composite-keys)?

You need
```
protected $primaryKey = 'customer_id';
protected $compositeKey = ['customer_id', 'agent_id'];
```
in your model, then you can use it like so:
```
$model->find(['customer_id' => 'value1', 'agent_id' => 'value2']);
```

**Comment by Geet2312** [comment]
Yes, I did follow the instruction and this implementation `$model->find(['customer_id' => 'value1', 'agent_id' => 'value2'])->update($attributes); ` works perfectly fine now. But this update is done by performing two operations, right? 

1.  Scan operation to find the data 
2. UpdateItem operation to update the data 
Please, correct me if I'm wrong.

**Comment by zoe-edwards** [comment]
Yeah the nature of Laravel and Eloquent is that it’ll fetch anything that you find.

If you directly use the `DynamoDb` facade, you can update it – but it’s not something that fits in with the Eloquent way of working.

    use BaoPham\DynamoDb\Facades\DynamoDb;

    $key // string
    $attribute // string
    $value

    DynamoDb::table('YourTable')
        ->setKey(DynamoDb::marshalItem(['id' => $key]))
        ->setUpdateExpression('SET #a = :v')
        ->setExpressionAttributeName('#a', $attribute)
        ->setExpressionAttributeValue(':v', DynamoDb::marshalValue($value))
        ->setReturnValues('ALL_NEW')
        ->prepare(DynamoDb::client('aws_connection'))
        ->updateItem();

And that will write without a read.

**Comment by Geet2312** [comment]
Thank you @zoe-edwards  for enlightening me. This facade implementation will do for me 👍.
