### ISSUE TITLE
How to use 'Sort descending'

### ISSUE THREAD

**Issue by SoftrainHere** [baopham/laravel-dynamodb#265]
My model looks like this

    protected $dynamoDbIndexKeys = [
      'event_from-created_at-index' => [
        'hash' => 'event_from',
        'range' => 'created_at'
      ],
    ];

and I am using sort query like this

    Log::query()
      ->withIndex('event_from-created_at-index') 
      ->decorate(function (RawDynamoDbQuery $raw) { 
      $raw->query['ScanIndexForward'] = false; 
    }) 
    ->get(); 

and it shows me like below

created_at: 2022-12-07 08:50:16   
created_at: 2022-12-08 08:50:16
created_at: 2022-12-09 08:50:16

actually It works on aws console 
![제목 없음](https://user-images.githubusercontent.com/86089013/206952219-50c35c26-00cb-4707-94f7-e26ef6566c10.png)

I set my partition / sort key like below
![제목 없음2](https://user-images.githubusercontent.com/86089013/206955164-1a484d97-b8e4-4731-9e39-6f8ce78e9576.png)

this is my Global secondary indexes
![제목 없음1](https://user-images.githubusercontent.com/86089013/206955059-0b5501c8-a5ed-4ff1-9f52-ae56f723d6e8.png)

Can you help me what i should do for this?

**Comment by akshay-shopcircle** [comment]
@SoftrainHere 
If you have fixed this, can you share here as I'm also facing the same.
