### ISSUE TITLE
created_at/updated_at caveat

### ISSUE THREAD

**Issue by gbish** [baopham/laravel-dynamodb#30]
So yesterday, I ran into a fun issue, which resulted in a less than helpful error from Dynamo:

```
local.INFO: exception 'Aws\DynamoDb\Exception\DynamoDbException' with message 'Error executing "PutItem" on "http://localhost:8000"; AWS HTTP error: Client error: `POST http://localhost:8000` resulted in a `400 Bad Request` response:
{"__type":"com.amazon.coral.validate#ValidationException","message":"Type mismatch for attribute to update"}
 ValidationException (client): Type mismatch for attribute to update - {"__type":"com.amazon.coral.validate#ValidationException","message":"Type mismatch for attribute to update"}'
```

It took me a while to track down the issue, but eventually found it was due to Eloquent converting my Carbon timestamp into a DateTime. This caused the error, as I had set my `created_at` field to be a `Number` type, and obviously, strings aren't numbers.

So, after all of this, it might be worth adding a caveat into the readme, stating if you wish to use `created_at`/`updated_at` in your table, you should override the `getDates()` method on your model.

Mine looks like this:

```
/**
 * {@inheritdoc}
 */
public function getDates() {
    return [];
}
```

**Comment by baopham** [comment]
Thanks for flagging. I want to understand the problem a bit better. What do you mean by "as I had set my created_at field to be a `Number` type"? Can you give the code that produces that error? That would help me have a better understanding.

**Comment by gbish** [comment]
Sure, so a colleague of mine created a job that would create the tables programatically via the command line, here's the code which creates the table in question:

```
'TableName'            => 'downloads',
'KeySchema'            => [
    [
        'AttributeName' => 'uuid',
        'KeyType'       => 'HASH',
    ],
    [
        'AttributeName' => 'created_at',
        'KeyType'       => 'RANGE',
    ],
],
'AttributeDefinitions' => [
    [
        'AttributeName' => 'uuid',
        'AttributeType' => 'S',
    ],
    [
        'AttributeName' => 'created_at',
        'AttributeType' => 'N',
    ],
    [
        'AttributeName' => 'download_id',
        'AttributeType' => 'S',
    ],
    [
        'AttributeName' => 'download_status',
        'AttributeType' => 'S',
    ],
],
```

The `created_at` field is part of my composite key, so I have to specify it's type, which is defined as `N` within the `AttributeDefinitions` for Number.

Within Eloquent in `Model.php`, `created_at` and `updated_at` are converted into DateTime strings via some magic:

```
public function getDates()
{
    $defaults = [static::CREATED_AT, static::UPDATED_AT];

    return $this->timestamps ? array_merge($this->dates, $defaults) : $this->dates;
}
```

This is more of an issue if you want to store a timestamp over the DateTime string.

**Comment by baopham** [comment]
Great. Thanks! I'll reproduce it on my end first.

**Comment by zoul0813** [comment]
Setting the models $dateFormat to 'U' (`Seconds since the Unix Epoch (January 1 1970 00:00:00 GMT)`)  should result in Eloquent automatically converting the Carbon object to a number.  The latest pending pull request also adds support for automatically setting created_at and updated_at values, and uses the $dateFormat for this as well.
