### ISSUE TITLE
laravel 5.3 error... anyone know what the problem? using localhost

### ISSUE THREAD

**Issue by bluevyjohn** [baopham/laravel-dynamodb#32]
Error 1:
ClientException in RequestException.php line 111:
Client error: `POST https://dynamodb.ap-southeast-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"com.amazon.coral.service#AccessDeniedException","Message":"User: arn:aws:iam::893977949585:user/abc is not a (truncated...)

Error 2:
DynamoDbException in WrappedHttpHandler.php line 192:
Error executing "Scan" on "https://dynamodb.ap-southeast-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://dynamodb.ap-southeast-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"com.amazon.coral.service#AccessDeniedException","Message":"User: arn:aws:iam::893977949585:user/abc is not a (truncated...)

Model
<?php
namespace App;
use BaoPham\DynamoDb\DynamoDbModel as Eloquent;
use Illuminate\Database\Eloquent\Model;

class DynamoDb extends Eloquent {

```
protected $table = 'users';

protected $primaryKey = 'user_name';
```

}
?>

route
Route::get('dynamodb',function(){
$user = \App\DynamoDb::all();
    print_r($user);

.env
DYNAMODB_KEY=AKIA...
DYNAMODB_SECRET=Ixnbox....
DYNAMODB_REGION=ap-southeast-1

**Comment by baopham** [comment]
Seems like permission error. Can you check if the access key and secret key have the right access to your dynamodb table?

**Comment by bluevyjohn** [comment]
Seen solved after i add AmazonDynamoDBFullAccesswithDataPipeline policy to user.

Between i get a problem for sentinel login register etc~
i had follow below mongodb sentinel modify few chged for amazon dynamodb
https://gist.github.com/Bodom78/a046363eeb79b6066119

use Jenssegers\MongoDB\Model as Eloquent; to use BaoPham\DynamoDb\DynamoDbModel as Eloquent;

did you know what's the problem? Thanks.
Client error: `POST https://dynamodb.ap-southeast-1.amazonaws.com` resulted in a `400 Bad Request` response:
{"__type":"com.amazon.coral.validate#ValidationException","message":"One or more parameter values were invalid: Comparis (truncated...)

**Comment by baopham** [comment]
can you give the code that is causing the error and your table schema?

**Comment by bluevyjohn** [comment]
Route::get('dynamodb',function(){
    if(\Sentinel::authenticate(array('admin@admin.com', 'admin'),0)) {
        echo "ok";
    }
    else{
         echo "not ok";
      }
});

![1](https://cloud.githubusercontent.com/assets/23025406/19671275/317d2d1a-9aa0-11e6-91f1-6d6dd67bd5ca.JPG)
![2](https://cloud.githubusercontent.com/assets/23025406/19671276/318764a6-9aa0-11e6-9e11-b96fdb3a2dcc.JPG)
![3](https://cloud.githubusercontent.com/assets/23025406/19671277/318b90da-9aa0-11e6-8f03-4aaee14a2422.JPG)

or can you suggest any user auth , role , permission laravel suitable for amazon dynamodb? Thanks...

**Comment by baopham** [comment]
Are you using DynamoDB for everything? seems like you have users and roles relationship - a relational DB like MySQL would be more suitable for these models.

You can have separate models (that don't need relationship) for DynamoDB only.

**Comment by bluevyjohn** [comment]
Yes, I need to use DynamoDb for everything. Can I have a example separate models (that don't need relationship) for DynamoDB? Sorry I am new for dynamoDB...

**Comment by baopham** [comment]
Depends on your application. This is more of a google task :) I can't really summarize it here when it is appropriate to use DynamoDB. But something a long this line:

```
class SomeModel extends \BaoPham\DynamoDb\DynamoDbModel {

}
```

```
class User extends \Illuminate\Database\Eloquent\Model {

}
```

**Comment by baopham** [comment]
Close due to inactivity
