### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by ctf0** [baopham/laravel-dynamodb#33]
i have installed the package & updated the dynamo version to the newest (2016-05-17_1.0) and now am kinda lost

- the dynamo config is added to services, which mean i have to use a db or else i would get 
` SQLSTATE[HY000] [2002] No such file or directory`

- am using dynamo in local, and am not sure do i still need to add the `key & secret` or not

**Comment by baopham** [comment]
> am using dynamo in local
If you're using local dynamodb, you don't need a key and secret, but the credential and region will determine the DB filename (see: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html)

I assume you have setup local dynamodb correctly according to its docs? Make sure to run the jar to spin up your local dynamodb.

It's hard to know your issue exactly. But first thing first, make sure local dynamodb setup correctly or connect to the one on AWS with your key and secret. Then setup your models according to the README in this repo.

**Comment by ctf0** [comment]
here is what i have
```bash
# DYNAMODB_KEY=
# DYNAMODB_SECRET=
DYNAMODB_REGION=us-west-2
DYNAMODB_LOCAL_ENDPOINT=http://localhost:8000
DYNAMODB_LOCAL=true
```

i have ran `java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb` from 
`vendor/baopham/dynamodb/dynamodb_local` and the console ran without any issues.

now for the db part, from what i understand that Dynamo works as a DB not a side service so i believe the config should be in **database.php** not **services.php** and unless we do so the user will have to have a second connection for the **pdo** or we would get an error because laravel needs a db connection to operate

**Comment by ctf0** [comment]
more of less we should have something like https://moloquent.github.io/master/#configuration

**Comment by baopham** [comment]
> because laravel needs a db connection to operate
This is not necessarily true. Laravel can work just fine without a DB providing that you don't have any DB models or something that needs a DB connection. 

As for where to put the config, it's not on my immediate todo list right now. 

You should download the local dynamodb separately. The one in this repo is only for the tests.

I suspect you have the default `User` model and that it's looking for the default DB connection.

**Comment by ctf0** [comment]
> Laravel can work just fine without a DB

okay, how how would u use dynamo with migration and seeders ?

> I suspect you have the default User model and that it's looking for the default DB connection.

nop, i have changed all the models to extend dynamo instead of laravel model

**Comment by baopham** [comment]
> how how would u use dynamo with migration and seeders
This is not supported. You will need to roll your own scripts unfortunately. 

You will need to provide more info on the logs and your setup in order for me to know the issue. E.g. steps to reproduce.

**Comment by ctf0** [comment]
am testing with a new laravel so
1- laravel new somthing
2- comp req ur package
3- add the config
4- change the model for user & post (something to test with)
5- get `SQLSTATE[HY000] [2002] No such file or directory` because laravel needs a working db connection

if its possible maybe u could follow the above steps and if u got it working, u can send it to me to cross-reference and see what am missing ?

**Comment by baopham** [comment]
> if its possible maybe u could follow the above steps and if u got it working, u can send it to me to cross-reference and see what am missing ?

Sure... but I can't say I would be able to do it anytime soon. End of next week maybe.

> on a side note, am kinda fuzzy on how to save data & retrieve it from dynamo if its not used as db or am i missing something ?

It is used as a DB but it will be on AWS so the feel might be a bit different than working with MySQL, etc.... have you played with it on AWS console?

**Comment by ctf0** [comment]
honestly i was using mysql then started playing with mongo "i even made a tool for it https://github.com/ctf0/MysqlToMongoDb" but the scaling in mongo is agonizing to say the least so i thought i would try dynamodb, 
the issue is from what i read from the examples on aws that its a key-value db "more like redis" but lots of articles says its more similar to mongo & that's why i thought i would play with it locally first, 
* see what it can and cant do would be
* the differences between it and mysql
* try it with an already made live code that works perfectlly on mysql "the same i did when trying mongo which aid in rapid understanding of the db"

and if all went well then take the next step which using the aws console it self and learn more about the scaling capabilities "more of learn to walk b4 running"

**Comment by ctf0** [comment]
@baopham any news

**Comment by baopham** [comment]
It would be easier for me to see what you currently have instead of the other way around. I have limited time right now.

**Comment by ctf0** [comment]
its okay, thanx for all ur help 👍
