### ISSUE TITLE
Supported methods errors

### ISSUE THREAD

**Issue by soulivong** [baopham/laravel-dynamodb#34]
I got error when I try to use
 `$model->find(<id>);`

My code:
`$u = new User();`
`echo $u->find('anyID');`

Error:
`ErrorException in Str.php line 424:`
`Illegal offset type in isset `

As well as another function such as

`$result = $u->where('key', 'key value')->get();`
`print_r($result);`

Error:
`ErrorException in DynamoDbQueryBuilder.php line 295:`
`Array to string conversion`

My Laravel version is 5.3, The similar errors also occur in another method.

**Comment by baopham** [comment]
Could you give me your table schema and a row example?

**Comment by soulivong** [comment]
Here is my table schema
```
{
  "Table": {
    "AttributeDefinitions": [
      {
        "AttributeName": "id",
        "AttributeType": "S"
      }
    ],
    "TableName": "Users",
    "KeySchema": [
      {
        "AttributeName": "id",
        "KeyType": "HASH"
      }
    ],
    "TableStatus": "ACTIVE",
    "CreationDateTime": "2016-11-14T10:25:48.951Z",
    "ProvisionedThroughput": {
      "LastIncreaseDateTime": "1970-01-01T00:00:00.000Z",
      "LastDecreaseDateTime": "1970-01-01T00:00:00.000Z",
      "NumberOfDecreasesToday": 0,
      "ReadCapacityUnits": 10,
      "WriteCapacityUnits": 10
    },
    "TableSizeBytes": 461,
    "ItemCount": 2,
    "TableArn": "arn:aws:dynamodb:ddblocal:000000000000:table/Users"
  }
}
```

Here is my sample data
```
{
      "name": "Soulivong",
      "password": "$2y$10$08ny2ScEiiLKQqCVgdO66uUKQLw7DTI6Txtsl5KAtEU86BbJuQyOG",
      "id": "77fb5440-ab21-11e6-8592-95fa5b88afc1",
      "is_active": true,
      "remember_token": "445259e986eede7cfdb60826bb10ee910bafbc02792f8792739d4ca5a4ab",
      "email": "soulivongfc@gmail.com"
}
```

**Comment by baopham** [comment]
Thanks! I'll get back to you soon.

**Comment by soulivong** [comment]
thank you very much

**Comment by soulivong** [comment]
Thank you so much for helping. Finally, I found a solution.
Because I made a mistake in declaring id in User class
`protected $primaryKey = ['id'];`
instead of 
`protected $primaryKey = 'id';`
it's simply stupid mistake, sorry.

**Comment by baopham** [comment]
Phew! Great. Thanks!

**Comment by soulivong** [comment]
May I ask you one more question?
Can you give me some recommendation on how to implement authentication function?

**Comment by baopham** [comment]
My recommendation would be to use Laravel default authentication workflow. e.g. use SQL db (mysql, postgres, etc.) for your User model. I'm not sure if DynamoDB is a good fit for User authentication. You can have separate models that are for DynamoDB.

**Comment by soulivong** [comment]
I see, I will try to implement in a different way.
Baopham solved a lot of my problems, Once again thank you very much.
