### ISSUE TITLE
Set IndexName manually?

### ISSUE THREAD

**Issue by vanquang9387** [baopham/laravel-dynamodb#40]
Hi, I have this:
```
protected $dynamoDbIndexKeys = [
    'user_id'   => 'user_index',
    'flg_state' => 'state_index',
];
```
It works as expected when there is one condition at once:
```
$this->where('user_id', 'abc-xyz')->get();
$this->where('flg_state', 0)->get();
```
But when there are multiple conditions
```
$this->where('user_id', 'abc-xyz')->where('flg_state', 0)->get();
```
I can not specify which index I want to use.

Is it OK to have a function to set IndexName manually like `$this->indexName('index_name');` ?

**Comment by baopham** [comment]
I will need to check the DynamoDB docs for this.

**Comment by baopham** [comment]
This is now in v4.1.0
