### ISSUE TITLE
Query Supported Operators

### ISSUE THREAD

**Issue by vanquang9387** [baopham/laravel-dynamodb#41]
Currently, laravel-dynamodb only supports `EQ` for key condition.
But, supported operators are varied by Partition Key and Sort Key for Query.
Partition Key operator
```
EQ
```

Sort Key operators
```
EQ | LE | LT | GE | GT | BEGINS_WITH | BETWEEN
```

Ref
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.KeyConditions.html

If I have this `protected $compositeKey = ['parent_id', 'id'];`
When execute `$this->where('parent_id', 100)->where('id', '>', 100)->get();` will give this condition: `parent_id EQ 100 AND id EQ 100`. Any operators for id (sort key) will become `EQ`;

**Comment by vanquang9387** [comment]
#42 solve this problem for composite indexes

**Comment by baopham** [comment]
Can you confirm if this can be closed?

**Comment by vanquang9387** [comment]
@baopham Not yet, #42 solve this problem for composite indexes only.

For table, when range (sort) key is other than `EQ`, a normal `Query` or `Scan` should be built, which is similar to how index currently done with.

**Comment by baopham** [comment]
Is it possible for you to share the schema? I'm not sure if I understand the other use case that you described

**Comment by vanquang9387** [comment]
@baopham assume that we have this key schema
```javascript
    KeySchema: [ // The type of of schema.  Must start with a HASH type, with an optional second RANGE.
        { // Required HASH type attribute
            AttributeName: 'id',
            KeyType: 'HASH',
        },
        {
            AttributeName: 'id2',
            KeyType: 'RANGE',
        }
    ],
```
When we do a query:
```php
$model->where('id', 100)->where('id2', '>', 10)->get();
```
Currently, `>` operator on `id2` will be ignored and acts like `=` (`EQ`)
Because of [this check](https://github.com/baopham/laravel-dynamodb/blob/master/src/DynamoDbQueryBuilder.php#L210)
```php
        if ($conditionValue = $this->conditionsContainKey()) {
            $item = $this->find($conditionValue, $columns);
            return new Collection([$item]);
        }
```

**Comment by baopham** [comment]
I think this solves it:

https://github.com/baopham/laravel-dynamodb/blob/fabd20d1645990198e2fe38b4111f49a71ad5f3b/tests/DynamoDbCompositeModelTest.php#L205-L229

https://github.com/baopham/laravel-dynamodb/blob/fabd20d1645990198e2fe38b4111f49a71ad5f3b/src/DynamoDbQueryBuilder.php#L493-L499

**Comment by baopham** [comment]
Closing as it seems to be resolved (see comment above)
