### ISSUE TITLE
EC2 IAM Role

### ISSUE THREAD

**Issue by hakimirahim** [baopham/laravel-dynamodb#48]
Hi,
how do i use this with EC2 IAM role instead of access keys? kindly help. thank you

**Comment by baopham** [comment]
Good question.

Found this in the docs: "If no credentials are provided, the SDK will attempt to load them from the environment". Have you tried to not set anything and see? Ultimately, you can write your own service provider (replace `BaoPham\DynamoDb\DynamoDbServiceProvider::class` with your own in the `config/app.php` which should look like [DynamoDbServiceProvider](https://github.com/baopham/laravel-dynamodb/blob/master/src/DynamoDbServiceProvider.php) with the exception that you will [pass in](https://github.com/baopham/laravel-dynamodb/blob/2e77e86c5c5bf/src/DynamoDbServiceProvider.php#L41) `$config` but without `credentials`.

**Comment by michaelshaffer37** [comment]
@hakimirahim  Just for clarity, have you [created an instance profile](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html), and assigned the role to that profile?

**Comment by hakimirahim** [comment]
just managed to dive into this project again.
the solution that works is by creating my own service provider as suggested. completely removing the credentials from $config made it work.

Thank you

**Comment by stemis** [comment]
@baopham 
Hi Baopham

First of all, I appreciate you writing this plugin and I will be happy to use it with my project!

About this issue:
As this is the most "best-practice" method to identify yourself with the AWS API's, I think this should be a feature of your project.

If adding a simple empty statement checking for any of the 'key', 'secret' or 'token' vars could delete the whole 'credentials' item from the array could solve this issue. This would mean that I do not have to clone your Service Provider and can use the package out of the box.

Do you think it is a possibility to add this feature?

Thank you.

Steff

**Comment by baopham** [comment]
Ah yeah, this should be easy to do.

**Comment by baopham** [comment]
@hakimirahim @stemis 
This should work now. You just need to leave these envs `DYNAMODB_KEY`, `DYNAMODB_SECRET`, `AWS_SESSION_TOKEN` empty

**Comment by stemis** [comment]
@baopham 

Should do yes!
Thank you for the quick response :)
