### ISSUE TITLE
isDirty() after retrieving models

### ISSUE THREAD

**Issue by zoul0813** [baopham/laravel-dynamodb#51]
Models appear to be dirty after retrieving them.

When using a standard Eloquent model, isDirty() returns false after retrieving it ...however, DynamoDbModel instances appear to be dirty after retrieving them which makes it hard to tell whether or not the model is actually dirty.

**Comment by baopham** [comment]
Ah yeah, I didn't consider `isDirty`. Nice catch.

**Comment by zoul0813** [comment]
I believe this one is as simple as calling `$model->syncOriginal()` whenever you call '$model->setUnfillableAttributes($item);` .. so far, my tests show this to be correct.

**Comment by zoul0813** [comment]
Ref #58
