### ISSUE TITLE
Call to a member function getClient() on null

### ISSUE THREAD

**Issue by zoul0813** [baopham/laravel-dynamodb#59]
This may be related to all the recent changes, ... and maybe I didn't update something I should have ... 

```bash
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                      
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
                                                           
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Call to a member function getClient() on null            
                                                           

Script php artisan optimize handling the post-update-cmd event returned with error code 1
```

This seems to be related to calling `$this->dynamoDb->getClient()` inside of DynamoDbModel ... looks like this is a recent change.  I believe I was previously using 4.0 or 4.1 - are there any config changes needed to support 5.0?

**Comment by zoul0813** [comment]
Ahh, looks like it may be related to the observer I have attached to my model.

```
(1/1) FatalThrowableError
Call to a member function getClient() on null
in DynamoDbModel.php (line 113)
at DynamoDbModel->setupDynamoDb()
in DynamoDbModel.php (line 76)
at DynamoDbModel->__construct()
in HasEvents.php (line 35)
at Model::observe('App\\Listeners\\ListingObserver')
in EventServiceProvider.php (line 40)
at EventServiceProvider->boot()
at call_user_func_array(array(object(EventServiceProvider), 'boot'), array())
in BoundMethod.php (line 29)
at BoundMethod::Illuminate\Container\{closure}()
in BoundMethod.php (line 87)
```

Looks like the EventServiceProvider is creating an instance of the model before the DynamoDbServiceProvider is created ...

**Comment by zoul0813** [comment]
Putting `BaoPham\DynamoDb\DynamoDbServiceProvider::class` before my `App\Providers\EventServiceProvider::class` fixed the problem.

**Comment by baopham** [comment]
Cool. Hope this can be closed now.

**Comment by zoul0813** [comment]
Yes, this can be closed - but perhaps a note added to the setup section about the order of the providers? Not sure if this is a common thing or not.
