### ISSUE TITLE
find/findOrFail do not support passing an array of ID's to find

### ISSUE THREAD

**Issue by zoul0813** [baopham/laravel-dynamodb#62]
Per the documentation, https://laravel.com/docs/5.4/eloquent#retrieving-single-models, find/findOrFail should support passing an array of ID's.  Currently, DynamoDbQueryBuilder treats an array of ID's as a composite key lookup preventing you from passing multiple non-composite key ID's ... or multiple composite key ID's to retrieve many records by ID.

**Comment by baopham** [comment]
Yeah, unfortunately, it's not supported. Finding multiple ids require to do a `whereIn` but `contains` is not a supported operation for `Query`.
