### ISSUE TITLE
Using BaoPham\DynamoDb\ModelTrait causes an error

### ISSUE THREAD

**Issue by cyberkiko** [baopham/laravel-dynamodb#64]
Hi, this trait is causing an error since is trying to use a method that is not defined in the Model class `getTableName()` it should use `getTable()` as is used in the rest of the library. 
```
FatalThrowableError
Call to undefined method BaoPham\DynamoDb\DynamoDbQueryBuilder::getTableName()
```
I don't find any definition of that function in the library neither in Laravel framework so I assume is a mistake in the name. 

Thanks @baopham

**Comment by RoyHP** [comment]
Having this issue as well

- laravel-dynamodb 0.5.0
- laravel 5.4.27

**Comment by baopham** [comment]
Ah, haven't used this trait for a long time. Feel free to create a PR :)

**Comment by RoyHP** [comment]
I submitted PR #65
