### ISSUE TITLE
Instances of Aws\DynamoDb\DynamoDbClient cannot be serialized

### ISSUE THREAD

**Issue by zoul0813** [baopham/laravel-dynamodb#71]
When trying to cache collections, this error appears.

Seems this simple fix solves the problem.  Though it may need to be evaluated a bit to make sure it recreates a proper DynamoDbModel instance when unserialized.  `$this->toArray()` may also be the wrong way to access the data, the smallest possible data set should be returned to reduce memory requirements for caching layers.

# DynamoDbModel.php
```
<?php

namespace BaoPham\DynamoDb;

use Exception;
use DateTime;
use Serializable;
use Illuminate\Database\Eloquent\Model;

/**
 * Class DynamoDbModel.
 */
abstract class DynamoDbModel extends Model implements Serializable
{
    // clipped rest of class

    public function serialize() {
        return serialize($this->toArray());
    }

    public function unserialize($data) {
        $arr = unserialize($data);
        $this->fill($arr);
        $this->setUnfillableAttributes($arr);
        $this->syncOriginal();
    }

}

**Comment by baopham** [comment]
Can you give the code that attempts to do the caching?

**Comment by zoul0813** [comment]
Happens when I try to cache just about anything ... here's an example

```
$results = $this->cache->remember('cache-key', $minutes, function() {
  return MyModel::all();
});
```

`$this->cache` is an instance of `Illuminate\Contracts\Cache\Repository` (in this case, a file cache for local testing)

**Comment by zoul0813** [comment]
After reviewing my code a bit more, looks like the following would work better for `unserialize($data)` 

```
public function unserialize($data) {
  $this->__construct(unserialize($data));
}
```
This is because unserialize is called instead of __construct when deserializing a Serializable object ... the model's __construct already accepts an array of data being passed in to build it, and bootstraps the model and sets up the client ... so the simpler approach is probably best here.

**Comment by baopham** [comment]
Good catch btw. This is now resolved.
