### ISSUE TITLE
I need to be retrieved only table values but result contain objects itself.

### ISSUE THREAD

**Issue by iamkarthick** [baopham/laravel-dynamodb#74]
##Dynamodb local database##

**Table**

var params = {
    TableName: 'docpanel-auditlogs-trials',
    KeySchema: [
        { 
            AttributeName: '_id',
            KeyType: 'HASH',
        }
    ],
    AttributeDefinitions: [ 
        {
            AttributeName: '_id',
            AttributeType: 'S', 
        }
    ],
    ProvisionedThroughput: { 
        ReadCapacityUnits: 100, 
        WriteCapacityUnits: 100, 
    }
};
dynamodb.createTable(params, function(err, data) {
    if (err) ppJson(err); 
    else ppJson(data);

});

###Inserted values are###

var params = {
    TableName: 'docpanel-auditlogs-trials',
    Item: { 
        "_id":"1256H-2334A-dsrt1",
         "user_id":"NULL",
          "case_id":"NULL",
          "action_type": "Login",
          "log_type":"NULL",
          "invoke_time": "2017-07-19 10:52:18",
          "actions": {
            "case_id": "101",
            "status": "read"
          }
    }
};
docClient.put(params, function(err, data) {
    if (err) ppJson(err); 
    else ppJson(data); 
});
------------------------------------------------------------------------------------------------------------

**Model**

namespace App;

class Dynamodb extends \BaoPham\DynamoDb\DynamoDbModel 
{
        
    protected $fillable = ['_id', 'case_id', 'count','action_type','log_type','invoke_time'];

    protected $table = 'docpanel-auditlogs-trials';

    public $timestamps = true;

	
}

**Controller**
use App\Dynamodb;

class DynamodbController extends Controller
  {
  
    public function get(Request $request) {

        $dynamodbObj=new Dynamodb();
       $result=$dynamodbObj->where('_id', '1256H-2334A-dsrt1')->get();
       print_r($result);
       exit;
    }
}

Results contain the all the objects. I need to retrieved  table values.

**Comment by baopham** [comment]
Please reformat your issue and state your issue clearly.

**Comment by iamkarthick** [comment]
@baopham  I got the result like  following format

Illuminate\Database\Eloquent\Collection Object ( [items:protected] => Array ( [0] => App\Dynamodb Object ( [fillable:protected] => Array ( [0] => _id [1] => case_id [2] => count [3] => action_type [4] => log_type [5] => invoke_time ) [table:protected] => docpanel-auditlogs-trials [timestamps] => 1 [incrementing] => [client:protected] => Aws\DynamoDb\DynamoDbClient Object ( [config:Aws\AwsClient:private] => Array ( [signature_version] => v4 [signing_name] => dynamodb [signing_region] => stub ) [region:Aws\AwsClient:private] => stub [endpoint:Aws\AwsClient:private] => GuzzleHttp\Psr7\Uri Object ( [scheme:GuzzleHttp\Psr7\Uri:private] => http [userInfo:GuzzleHttp\Psr7\Uri:private] => [host:GuzzleHttp\Psr7\Uri:private] => localhost [port:GuzzleHttp\Psr7\Uri:private] => 8000 [path:GuzzleHttp\Psr7\Uri:private] => [query:GuzzleHttp\Psr7\Uri:private] => [fragment:GuzzleHttp\Psr7\Uri:private] => ) [api:Aws\AwsClient:private] => Aws\Api\Service Object ( [apiProvider:Aws\Api\Service:private] => Aws\Api\ApiProvider Object ( [manifest:Aws\Api\ApiProvider:private] => Array ( [acm] => Array ( [namespace] => Acm [versions] => Array ( [latest] => 2015-12-08 [2015-12-08] => 2015-12-08 ) ) [apigateway] => Array ( [namespace] => ApiGateway [versions] => Array ( [latest] => 2015-07-09 [2015-07-09] => 2015-07-09 [2015-06-01] => 2015-07-09 ) ) [application-autoscaling] => Array ( [namespace] => ApplicationAutoScaling [versions] => Array ( [latest] => 2016-02-06 [2016-02-06] => 2016-02-06 ) ) [appstream] => Array ( [namespace] => Appstream [versions] => Array ( [latest] => 2016-12-01 [2016-12-01] => 2016-12-01 ) ) [athena] => Array ( [namespace] => Athena [versions] => Array ( [latest] => 2017-05-18 [2017-05-18] => 2017-05-18 ) ) [autoscaling] => Array ( [namespace] => AutoScaling [versions] => Array ( [latest] => 2011-01-01 [2011-01-01] => 2011-01-01 ) ) [batch] => Array ( [namespace] => Batch [versions] => Array ( [latest] => 2016-08-10 [2016-08-10] => 2016-08-10 ) ) [budgets] => Array ( [namespace] => Budgets [versions] => Array ( [latest] => 2016-10-20 [2016-10-20] => 2016-10-20 ) ) [clouddirectory] => Array ( [namespace] => CloudDirectory [versions] => Array ( [latest] => 2016-05-10 [2016-05-10] => 2016-05-10 ) ) [cloudformation] => Array ( [namespace] => CloudFormation [versions] => Array ( [latest] => 2010-05-15 [2010-05-15] => 2010-05-15 ) ) [cloudfront] => Array ( [namespace] => CloudFront [versions] => Array ( [latest] => 2017-03-25 [2017-03-25] => 2017-03-25 [2016-11-25] => 2016-11-25 [2016-09-29] => 2016-09-29 [2016-09-07] => 2016-09-07 [2016-08-20] => 2016-08-20 [2016-08-01] => 2016-08-01 [2016-01-28] => 2016-01-28 [2016-01-13] => 2017-03-25 [2015-09-17] => 2017-03-25 [2015-07-27] => 2015-07-27 [2015-04-17] => 2015-07-27 [2014-11-06] => 2015-07-27 ) ) [cloudhsm] => Array ( [namespace] => CloudHsm [versions] => Array ( [latest] => 2014-05-30 [2014-05-30] => 2014-05-30 ) ) [cloudsearch] => Array ( [namespace] => CloudSearch [versions] => Array ( [latest] => 2013-01-01 [2013-01-01] => 2013-01-01 ) ) [cloudsearchdomain] => Array ( [namespace] => CloudSearchDomain [versions] => Array ( [latest] => 2013-01-01 [2013-01-01] => 2013-01-01 ) ) [cloudtrail] => Array ( [namespace] => CloudTrail [versions] => Array ( [latest] => 2013-11-01 [2013-11-01] => 2013-11-01 ) ) [codebuild] => Array ( [namespace] => CodeBuild [versions] => Array ( [latest] => 2016-10-06 [2016-10-06] => 2016-10-06 ) ) [codecommit] => Array ( [namespace] => CodeCommit [versions] => Array ( [latest] => 2015-04-13 [2015-04-13] => 2015-04-13 ) ) [codedeploy] => Array ( [namespace] => CodeDeploy [versions] => Array ( [latest] => 2014-10-06 [2014-10-06] => 2014-10-06 ) ) [codepipeline] => Array ( [namespace] => CodePipeline [versions] => Array ( [latest] => 2015-07-09 [2015-07-09] => 2015-07-09 ) ) [codestar] => Array ( [namespace] => CodeStar [versions] => Array ( [latest] => 2017-04-19 [2017-04-19] => 2017-04-19 ) ) [cognito-identity] => Array ( [namespace] => CognitoIdentity [versions] => Array ( [latest] => 2014-06-30 [2014-06-30] => 2014-06-30 ) ) [cognito-idp] => Array ( [namespace] => CognitoIdentityProvider [versions] => Array ( [latest] => 2016-04-18 [2016-04-18] => 2016-04-18 ) ) [cognito-sync] => Array ( [namespace] => CognitoSync [versions] => Array ( [latest] => 2014-06-30 [2014-06-30] => 2014-06-30 ) ) [config] => Array ( [namespace] => ConfigService [versions] => Array ( [latest] => 2014-11-12 [2014-11-12] => 2014-11-12 ) ) [cur] => Array ( [namespace] => CostandUsageReportService [versions] => Array ( [latest] => 2017-01-06 [2017-01-06] => 2017-01-06 ) ) [data.iot] => Array ( [namespace] => IotDataPlane [versions] => Array ( [latest] => 2015-05-28 [2015-05-28] => 2015-05-28 ) ) [datapipeline] => Array ( [namespace] => DataPipeline [versions] => Array ( [latest] => 2012-10-29 [2012-10-29] => 2012-10-29 ) ) [dax] => Array ( [namespace] => DAX [versions] => Array ( [latest] => 2017-04-19 [2017-04-19] => 2017-04-19 ) ) [devicefarm] => Array ( [namespace] => DeviceFarm [versions] => Array ( [latest] => 2015-06-23 [2015-06-23] => 2015-06-23 ) ) [directconnect] => Array ( [namespace] => DirectConnect [versions] => Array ( [latest] => 2012-10-25 [2012-10-25] => 2012-10-25 ) ) [discovery] => Array ( [namespace] => ApplicationDiscoveryService [versions] => Array ( [latest] => 2015-11-01 [2015-11-01] => 2015-11-01 ) ) [dms] => Array ( [namespace] => DatabaseMigrationService [versions] => Array ( [latest] => 2016-01-01 [2016-01-01] => 2016-01-01 ) ) [ds] => Array ( [namespace] => DirectoryService [versions] => Array ( [latest] => 2015-04-16 [2015-04-16] => 2015-04-16 ) ) [dynamodb] => Array ( [namespace] => DynamoDb [versions] => Array ( [latest] => 2012-08-10 [2012-08-10] => 2012-08-10 [2011-12-05] => 2011-12-05 ) ) [ec2] => Array ( [namespace] => Ec2 [versions] => Array ( [latest] => 2016-11-15 [2016-11-15] => 2016-11-15 [2016-09-15] => 2016-09-15 [2016-04-01] => 2016-04-01 [2015-10-01] => 2015-10-01 [2015-04-15] => 2016-11-15 ) ) [ecr] => Array ( [namespace] => Ecr [versions] => Array ( [latest] => 2015-09-21 [2015-09-21] => 2015-09-21 ) ) [ecs] => Array ( [namespace] => Ecs [versions] => Array ( [latest] => 2014-11-13 [2014-11-13] => 2014-11-13 ) ) [elasticache] => Array ( [namespace] => ElastiCache [versions] => Array ( [latest] => 2015-02-02 [2015-02-02] => 2015-02-02 ) ) [elasticbeanstalk] => Array ( [namespace] => ElasticBeanstalk [versions] => Array ( [latest] => 2010-12-01 [2010-12-01] => 2010-12-01 ) ) [elasticfilesystem] => Array ( [namespace] => Efs [versions] => Array ( [latest] => 2015-02-01 [2015-02-01] => 2015-02-01 ) ) [elasticloadbalancing] => Array ( [namespace] => ElasticLoadBalancing [versions] => Array ( [latest] => 2012-06-01 [2012-06-01] => 2012-06-01 ) ) [elasticloadbalancingv2] => Array ( [namespace] => ElasticLoadBalancingV2 [versions] => Array ( [latest] => 2015-12-01 [2015-12-01] => 2015-12-01 ) ) [elasticmapreduce] => Array ( [namespace] => Emr [versions] => Array ( [latest] => 2009-03-31 [2009-03-31] => 2009-03-31 ) ) [elastictranscoder] => Array ( [namespace] => ElasticTranscoder [versions] => Array ( [latest] => 2012-09-25 [2012-09-25] => 2012-09-25 ) ) [email] => Array ( [namespace] => Ses [versions] => Array ( [latest] => 2010-12-01 [2010-12-01] => 2010-12-01 ) ) [entitlement.marketplace] => Array ( [namespace] => MarketplaceEntitlementService [versions] => Array ( [latest] => 2017-01-11 [2017-01-11] => 2017-01-11 ) ) [es] => Array ( [namespace] => ElasticsearchService [versions] => Array ( [latest] => 2015-01-01 [2015-01-01] => 2015-01-01 ) ) [events] => Array ( [namespace] => CloudWatchEvents [versions] => Array ( [latest] => 2015-10-07 [2015-10-07] => 2015-10-07 [2014-02-03] => 2015-10-07 ) ) [firehose] => Array ( [namespace] => Firehose [versions] => Array ( [latest] => 2015-08-04 [2015-08-04] => 2015-08-04 ) ) [gamelift] => Array ( [namespace] => GameLift [versions] => Array ( [latest] => 2015-10-01 [2015-10-01] => 2015-10-01 ) ) [glacier] => Array ( [namespace] => Glacier [versions] => Array ( [latest] => 2012-06-01 [2012-06-01] => 2012-06-01 ) ) [greengrass] => Array ( [namespace] => Greengrass [versions] => Array ( [latest] => 2017-06-07 [2017-06-07] => 2017-06-07 ) ) [health] => Array ( [namespace] => Health [versions] => Array ( [latest] => 2016-08-04 [2016-08-04] => 2016-08-04 ) ) [iam] => Array ( [namespace] => Iam [versions] => Array ( [latest] => 2010-05-08 [2010-05-08] => 2010-05-08 ) ) [importexport] => Array ( [namespace] => ImportExport [versions] => Array ( [latest] => 2010-06-01 [2010-06-01] => 2010-06-01 ) ) [inspector] => Array ( [namespace] => Inspector [versions] => Array ( [latest] => 2016-02-16 [2016-02-16] => 2016-02-16 [2015-08-18] => 2016-02-16 ) ) [iot] => Array ( [namespace] => Iot [versions] => Array ( [latest] => 2015-05-28 [2015-05-28] => 2015-05-28 ) ) [kinesis] => Array ( [namespace] => Kinesis [versions] => Array ( [latest] => 2013-12-02 [2013-12-02] => 2013-12-02 ) ) [kinesisanalytics] => Array ( [namespace] => KinesisAnalytics [versions] => Array ( [latest] => 2015-08-14 [2015-08-14] => 2015-08-14 ) ) [kms] => Array ( [namespace] => Kms [versions] => Array ( [latest] => 2014-11-01 [2014-11-01] => 2014-11-01 ) ) [lambda] => Array ( [namespace] => Lambda [versions] => Array ( [latest] => 2015-03-31 [2015-03-31] => 2015-03-31 ) ) [lex-models] => Array ( [namespace] => LexModelBuildingService [versions] => Array ( [latest] => 2017-04-19 [2017-04-19] => 2017-04-19 ) ) [lightsail] => Array ( [namespace] => Lightsail [versions] => Array ( [latest] => 2016-11-28 [2016-11-28] => 2016-11-28 ) ) [logs] => Array ( [namespace] => CloudWatchLogs [versions] => Array ( [latest] => 2014-03-28 [2014-03-28] => 2014-03-28 ) ) [machinelearning] => Array ( [namespace] => MachineLearning [versions] => Array ( [latest] => 2014-12-12 [2014-12-12] => 2014-12-12 ) ) [marketplacecommerceanalytics] => Array ( [namespace] => MarketplaceCommerceAnalytics [versions] => Array ( [latest] => 2015-07-01 [2015-07-01] => 2015-07-01 ) ) [metering.marketplace] => Array ( [namespace] => MarketplaceMetering [versions] => Array ( [latest] => 2016-01-14 [2016-01-14] => 2016-01-14 ) ) [monitoring] => Array ( [namespace] => CloudWatch [versions] => Array ( [latest] => 2010-08-01 [2010-08-01] => 2010-08-01 ) ) [mturk-requester] => Array ( [namespace] => MTurk [versions] => Array ( [latest] => 2017-01-17 [2017-01-17] => 2017-01-17 ) ) [opsworks] => Array ( [namespace] => OpsWorks [versions] => Array ( [latest] => 2013-02-18 [2013-02-18] => 2013-02-18 ) ) [opsworkscm] => Array ( [namespace] => OpsWorksCM [versions] => Array ( [latest] => 2016-11-01 [2016-11-01] => 2016-11-01 ) ) [organizations] => Array ( [namespace] => Organizations [versions] => Array ( [latest] => 2016-11-28 [2016-11-28] => 2016-11-28 ) ) [pinpoint] => Array ( [namespace] => Pinpoint [versions] => Array ( [latest] => 2016-12-01 [2016-12-01] => 2016-12-01 ) ) [polly] => Array ( [namespace] => Polly [versions] => Array ( [latest] => 2016-06-10 [2016-06-10] => 2016-06-10 ) ) [rds] => Array ( [namespace] => Rds [versions] => Array ( [latest] => 2014-10-31 [2014-10-31] => 2014-10-31 [2014-09-01] => 2014-09-01 ) ) [redshift] => Array ( [namespace] => Redshift [versions] => Array ( [latest] => 2012-12-01 [2012-12-01] => 2012-12-01 ) ) [rekognition] => Array ( [namespace] => Rekognition [versions] => Array ( [latest] => 2016-06-27 [2016-06-27] => 2016-06-27 ) ) [resourcegroupstaggingapi] => Array ( [namespace] => ResourceGroupsTaggingAPI [versions] => Array ( [latest] => 2017-01-26 [2017-01-26] => 2017-01-26 ) ) [route53] => Array ( [namespace] => Route53 [versions] => Array ( [latest] => 2013-04-01 [2013-04-01] => 2013-04-01 ) ) [route53domains] => Array ( [namespace] => Route53Domains [versions] => Array ( [latest] => 2014-05-15 [2014-05-15] => 2014-05-15 ) ) [runtime.lex] => Array ( [namespace] => LexRuntimeService [versions] => Array ( [latest] => 2016-11-28 [2016-11-28] => 2016-11-28 ) ) [s3] => Array ( [namespace] => S3 [versions] => Array ( [latest] => 2006-03-01 [2006-03-01] => 2006-03-01 ) ) [servicecatalog] => Array ( [namespace] => ServiceCatalog [versions] => Array ( [latest] => 2015-12-10 [2015-12-10] => 2015-12-10 ) ) [shield] => Array ( [namespace] => Shield [versions] => Array ( [latest] => 2016-06-02 [2016-06-02] => 2016-06-02 ) ) [sms] => Array ( [namespace] => Sms [versions] => Array ( [latest] => 2016-10-24 [2016-10-24] => 2016-10-24 ) ) [snowball] => Array ( [namespace] => SnowBall [versions] => Array ( [latest] => 2016-06-30 [2016-06-30] => 2016-06-30 ) ) [sns] => Array ( [namespace] => Sns [versions] => Array ( [latest] => 2010-03-31 [2010-03-31] => 2010-03-31 ) ) [sqs] => Array ( [namespace] => Sqs [versions] => Array ( [latest] => 2012-11-05 [2012-11-05] => 2012-11-05 ) ) [ssm] => Array ( [namespace] => Ssm [versions] => Array ( [latest] => 2014-11-06 [2014-11-06] => 2014-11-06 ) ) [states] => Array ( [namespace] => Sfn [versions] => Array ( [latest] => 2016-11-23 [2016-11-23] => 2016-11-23 ) ) [storagegateway] => Array ( [namespace] => StorageGateway [versions] => Array ( [latest] => 2013-06-30 [2013-06-30] => 2013-06-30 ) ) [streams.dynamodb] => Array ( [namespace] => DynamoDbStreams [versions] => Array ( [latest] => 2012-08-10 [2012-08-10] => 2012-08-10 ) ) [sts] => Array ( [namespace] => Sts [versions] => Array ( [latest] => 2011-06-15 [2011-06-15] => 2011-06-15 ) ) [support] => Array ( [namespace] => Support [versions] => Array ( [latest] => 2013-04-15 [2013-04-15] => 2013-04-15 ) ) [swf] => Array ( [namespace] => Swf [versions] => Array ( [latest] => 2012-01-25 [2012-01-25] => 2012-01-25 ) ) [waf-regional] => Array ( [namespace] => WafRegional [versions] => Array ( [latest] => 2016-11-28 [2016-11-28] => 2016-11-28 ) ) [waf] => Array ( [namespace] => Waf [versions] => Array ( [latest] => 2015-08-24 [2015-08-24] => 2015-08-24 ) ) [workdocs] => Array ( [namespace] => WorkDocs [versions] => Array ( [latest] => 2016-05-01 [2016-05-01] => 2016-05-01 ) ) [workspaces] => Array ( [namespace] => WorkSpaces [versions] => Array ( [latest] => 2015-04-08 [2015-04-08] => 2015-04-08 ) ) [xray] => Array ( [namespace] => XRay [versions] => Array ( [latest] => 2016-04-12 [2016-04-12] => 2016-04-12 ) ) ) [modelsDir:Aws\Api\ApiProvider:private] => D:\xampp\htdocs\backend\vendor\aws\aws-sdk-php\src\Api/../data ) [serviceName:Aws\Api\Service:private] => dynamodb [apiVersion:Aws\Api\Service:private] => 2012-08-10 [operations:Aws\Api\Service:private] => Array ( [Scan] => Aws\Api\Operation Object ( [input:Aws\Api\Operation:private] => Aws\Api\StructureShape Object ( [members:Aws\Api\StructureShape:private] => Array ( [TableName] => Aws\Api\Shape Object ( [definition:protected] => Array ( [type] => string [max] => 255 [min] => 3 [pattern] => [a-zA-Z0-9_.-]+ [name] => TableName ) [shapeMap:protected] => Aws\Api\ShapeMap Object ( [definitions:Aws\Api\ShapeMap:private] => Array ( [AttributeAction] => Array ( [type] => string [enum] => Array ( [0] => ADD [1] => PUT [2] => DELETE ) ) [AttributeDefinition] => Array ( [type] => structure [required] => Array ( [0] => AttributeName [1] => AttributeType ) [members] => Array ( [AttributeName] => Array ( [shape] => KeySchemaAttributeName ) [AttributeType] => Array ( [shape] => ScalarAttributeType ) ) ) [AttributeDefinitions] => Array ( [type] => list [member] => Array ( [shape] => AttributeDefinition ) ) [AttributeMap] => Array ( [type] => map [key] => Array ( [shape] => AttributeName ) [value] => Array ( [shape] => AttributeValue ) ) [AttributeName] => Array ( [type] => string [max] => 65535 ) [AttributeNameList] => Array ( [type] => list [member] => Array ( [shape] => AttributeName ) [min] => 1 ) [AttributeUpdates] => Array ( [type] => map [key] => Array ( [shape] => AttributeName ) [value] => Array ( [shape] => AttributeValueUpdate ) ) [AttributeValue] => Array ( [type] => structure [members] => Array ( [S] => Array ( [shape] => StringAttributeValue ) [N] => Array ( [shape] => NumberAttributeValue ) [B] => Array ( [shape] => BinaryAttributeValue ) [SS] => Array ( [shape] => StringSetAttributeValue ) [NS] => Array ( [shape] => NumberSetAttributeValue ) [BS] => Array ( [shape] => BinarySetAttributeValue ) [M] => Array ( [shape] => MapAttributeValue ) [L] => Array ( [shape] => ListAttributeValue ) [NULL] => Array ( [shape] => NullAttributeValue ) [BOOL] => Array ( [shape] => BooleanAttributeValue ) ) ) [AttributeValueList] => Array ( [type] => list [member] => Array ( [shape] => AttributeValue ) ) [AttributeValueUpdate] => Array ( [type] => structure [members] => Array ( [Value] => Array ( [shape] => AttributeValue ) [Action] => Array ( [shape] => AttributeAction ) ) ) [Backfilling] => Array ( [type] => boolean ) [BatchGetItemInput] => Array ( [type] => structure [required] => Array ( [0] => RequestItems ) [members] => Array ( [RequestItems] => Array ( [shape] => BatchGetRequestMap ) [ReturnConsumedCapacity] => Array ( [shape] => ReturnConsumedCapacity ) ) ) [BatchGetItemOutput] => Array ( [type] => structure [members] => Array ( [Responses] => Array ( [shape] => BatchGetResponseMap ) [UnprocessedKeys] => Array ( [shape] => BatchGetRequestMap ) [ConsumedCapacity] => Array ( [shape] => ConsumedCapacityMultiple ) ) ) [BatchGetRequestMap] => Array ( [type] => map [key] => Array ( [shape] => TableName ) [value] => Array ( [shape] => KeysAndAttributes ) [max] => 100 [min] => 1 ) [BatchGetResponseMap] => Array ( [type] => map [key] => Array ( [shape] => TableName ) [value] => Array ( [shape] => ItemList ) ) [BatchWriteItemInput] => Array ( [type] =>

**Comment by baopham** [comment]
Can you please format the message using markdown: https://guides.github.com/features/mastering-markdown/ - see the Syntax Highlighting section.

I can't help if I can't read it...

**Comment by iamkarthick** [comment]
@baopham when try to call the following.

$dynamodbObj=new Dynamodb();
 $result=$dynamodbObj->where('_id', '1256H-2334A-dsrt1')->get();

the above code are running correctly but i got alot of result as i mentioned early msg.

**Comment by baopham** [comment]
Have you checked in the DB if the id is really unique?
Also, please set the property `protected $primaryKey = '_id';`  in your model.

**Comment by iamkarthick** [comment]
Yes @baopham I have set the primaryKey but it will retrieve the full page of result. But in the table it show only one record.

![image](https://user-images.githubusercontent.com/23172773/29209293-5e44cf48-7eab-11e7-92bc-e91278e2abe1.png)

**Comment by baopham** [comment]
From the model you gave me, I don't see that you set it as primary key. Please post the updated model again here. Please use markdown syntax...

**Comment by iamkarthick** [comment]
## Controller
![image](https://user-images.githubusercontent.com/23172773/29209444-29d92c1c-7eac-11e7-81f9-27f2e3ed78f8.png)

## Model

![image](https://user-images.githubusercontent.com/23172773/29209425-0a2ec1e2-7eac-11e7-9c7e-39a8d4cc24c3.png)

**Comment by baopham** [comment]
Please run this:
```php
$result = $dynamodbObj->where('_id', '1256H-2334A-dsrt1')->get()->toArray();
print_r($result);
```

And send a picture of the log.

**Comment by iamkarthick** [comment]
@baopham Thank you very much. Got the result. 

![image](https://user-images.githubusercontent.com/23172773/29209541-c5a4a676-7eac-11e7-9ade-3b193702d34f.png)

**Comment by baopham** [comment]
There it is...
```php
$result = $dynamodbObj->where('_id', '1256H-2334A-dsrt1')->get()
```
Maybe you should check out Laravel eloquent docs. By default it will give you the model instance so when you do `print_r`, it will print out all the properties of the instance.
