### ISSUE TITLE
toSql style method for logging purposes (toRequestJson ?)

### ISSUE THREAD

**Issue by zoul0813** [baopham/laravel-dynamodb#82]
Support for some sort of "toSql" style method, so the application can log requests to DynamoDb for various purposes.

I'm working on a PR for this now ... thought I had it, but forgot to test the "find" method ...

**Comment by zoul0813** [comment]
I've got "toRequestJson" working, ... here's the commit in my fork, 

https://github.com/zoul0813/laravel-dynamodb/commit/a54399dbbf3e6bd02d448ce0ff43d3620700a240 

Figured I'd let you review this before creating a PR for it ...

**Comment by baopham** [comment]
There's already`debug` mode support: https://github.com/baopham/laravel-dynamodb#install

**Comment by baopham** [comment]
I prefer to use AWS debug rather than roll out our own.

**Comment by zoul0813** [comment]
Can you explain how the `debug` support works? I've enabled it on my end, but I never see anything in the logs.  I've scanned through the code, and I don't see anything that uses it ... I can see a few `Log` facade calls in exception handling, but nothing that would indicate logging of queries being made, etc.

What is "AWS debug"?

**Comment by baopham** [comment]
http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html 

Which log did you check? did you set `debug` to `true`? AWS sdk will automatically log all queries, which I then route to Laravel logs.

**Comment by baopham** [comment]
You should see something like this:

![image](https://user-images.githubusercontent.com/783410/29412868-055b9128-838d-11e7-97f0-29350ffb11c1.png)

**Comment by zoul0813** [comment]
Yes, I managed to get this working yesterday ... forgot to update here.

I don't believe this type of logging solves my problem though, but I'll look into it and see if there's a way to get what I want/need out of this logging mechanism.  I'm not necessarily interested in "debug" logging, as I'd like to log requests on a production server for reporting purposes.

**Comment by baopham** [comment]
This is now in v4.1.0
