### ISSUE TITLE
Feature request: REMOVE Update Expression

### ISSUE THREAD

**Issue by jilster** [baopham/laravel-dynamodb#85]
I have some attributes in a lot of items that i would like to remove. I could do this by hand using the AWS management console, but i was thinking that it would maybe be a nice feature for laravel-dynamodb as well. Could you please integrate the REMOVE action for the Update Expressions? 

See: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.REMOVE

**Comment by baopham** [comment]
That would be an interesting feature. I don't have ETA for it unfortunately. Maybe next weekend, I'll have some time for this project.

**Comment by jilster** [comment]
That would be great!

**Comment by baopham** [comment]
It is now available in branch `remove-update-exp`. You can try by updating your `composer.lock` to use `dev-remove-update-exp`. Make sure you run `composer update && composer dump-autoload` after.

Just a note that based on the doc, you can only update one item at a time by specifying your primary key / composite key. 

Here is an example:

```php
$model = new Model();
$model->where('id', 'foo')->removeAttribute('name', 'description');
```

There's unit tests and all but don't use it in production yet :)

**Comment by jilster** [comment]
It works perfectly, thank you very much for doing this!

To remove all attributes at once, i did this:

```php
$models = Model::whereNotNull('attribute')->get();
foreach($models as $model) {
    $model = Model::where('id', $model->id)->removeAttribute('attribute');
}
```

**Comment by baopham** [comment]
Awesome! 👍 BTW, you could use `chunk` feature in case you have a lot of the items that satisfies the condition `whereNotNull('attribute')`, which could exceed the 1MB limit. 

Anyhow, thanks for helping me test this. I'm merging the PR.

**Comment by jilster** [comment]
O right, i forgot about chunk. Thanks again.

**Comment by baopham** [comment]
Try version `1.6.1` now. Btw you don't need to do another `where` query once you already have a model instance:

```php
$models = Model::whereNotNull('attribute')->get();
foreach($models as $model) {
    $model->removeAttribute('attribute');
}
```

**Comment by jilster** [comment]
Works like a charm, thank you for the advice.
