### ISSUE TITLE
Not able to use it like normal query builder

### ISSUE THREAD

**Issue by deepak-trimantra** [baopham/laravel-dynamodb#91]
If want fetch data from customers table and populate it in data-tables.

>         $customers = new Customer();
>         if ( $search != '' )
>         {
>                $customers->where( 'email', 'contains', $search );
>         }
>         $customers_data = $customers->take( $length )->get();

I am doing like this but it is not working, always getting data without where condition.

Then, I tried like this 
       

>         $customers = new Customer();
>         if ( $search != '' )
>         {
>              $customers_data  = $customers->where( 'email', 'contains', $search )->take($length)->get();
>         }
>         else
>         {
>               $customers_data = $customers->take( $length )->get();
>         }
> 

Then I get data with where condition. 

Please provide solution for this.

**Comment by baopham** [comment]
Well that is expected... It would behave the same for laravel eloquent. `where` returns you a new query builder. When you do `take` on the model it assumed a fresh new query. 

Just do this...

```php
$query = $customer->newQuery();
if ($search) $query->where(....);
return $query->take($length)->get();
```

**Comment by deepak-trimantra** [comment]
Thanks for quick response. It worked!

**Comment by deepak-trimantra** [comment]
Is orderBy available?

**Comment by baopham** [comment]
No, not as of now. You can check all the supported features here: https://github.com/baopham/laravel-dynamodb#supported-features 

Sorting in dynamodb would require a sort key. You can't arbitrarily sort by any column.
