### ISSUE TITLE
Error in DynamoDbQueryBuilder::__call

### ISSUE THREAD

**Issue by zoul0813** [baopham/laravel-dynamodb#93]
`$this->query->{$method}(...$parameters);` throws errors when you attempt to call methods on the model class that don't exist.

```Undefined property: BaoPham\DynamoDb\DynamoDbQueryBuilder::$query```

I believe this line should be commented out, as it's carried over from the Eloquent classes as part of the "scope" implementation and may be an unnecessary remnant of code that was left behind.

**Comment by baopham** [comment]
👍
