### ISSUE TITLE
Alternative Model Hyrdation

### ISSUE THREAD

**Issue by zoul0813** [baopham/laravel-dynamodb#94]
Just opening this up for discussion.  Curious about your thoughts on this.

I've been working with Elasticquent, and noticed that when they hydrate the models they use the following code:

```
    public static function newFromBuilderRecursive(
        Model $model,
        array $attributes = [],
        Relation $parentRelation = null
    ) {
        $instance = $model->newInstance([], $exists = true);

        $instance->setRawAttributes((array)$attributes, $sync = true);

        // Load relations recursive
        static::loadRelationsAttributesRecursive($instance);
        // Load pivot
        static::loadPivotAttribute($instance, $parentRelation);

        return $instance;
    }
```

The relevant lines there would be:

```
$instance = $model->newInstance([], $exists = true);
$instance->setRawAttributes((array)$attributes, $sync = true);
```

The reason this seems better is because "setRawAttributes" just sets the models internal attributes directly, bypassing guarded/unfillable logic and mutators.  Where `newInstance($item, true)` and `$model->setUnfillable($item)` calls setAttribute() which then calls mutators and performs other logic.

The updated DynamoDbQueryBuilder code to implement this new code would look something like this:

```
    protected function getAll($columns = [], $limit = -1, $use_iterator = true)
    {
        // snipped unrelated code

        $results = [];

        foreach ($iterator as $item) {
            $item = $this->model->unmarshalItem($item);
            $model = $this->model->newInstance([], $exists = true);
            $model->setRawAttributes($item, $sync = true);
            $results[] = $model;
        }
        
        return $this->getModel()->newCollection($results);
    }
```

This would make the DynmoDbModel::setUnfillable method obsolete, as there is no longer a reason to concern ourselves with fillable/unfillable data coming from the "source" (dynamodb).  

Data written to DynamoDb should be considered infallible when being used to hydrate a model.  

We also shouldn't be executing attribute mutators during hydration.

**Comment by baopham** [comment]
yep sounds good 👍 . Feel free to make a PR
