### ISSUE TITLE
Nested items

### ISSUE THREAD

**Issue by raskalbass** [baopham/laravel-dynamodb#98]
Hi!
How can i work with nested items?
get, update, remove methods?

example:
```
{
   id: 1,
   test: {  
        a: "test a",
        b: "test b"
   }
}
```
**GET**
I use your function $item = Model::find(1) and than try
`echo $item->test->a`
got error Trying to get property of non-object

**UPDATE**
method
`$item->test->a = 'another'; $item->save()`
just the same and function update() wasn't documented. How can I use it?

**REMOVE**
`$item->removeAttribute('test.a');` doing nothing
`$item->removeAttribute('test', 'a');` remove all test records

This feature dont work at all or I do something wrong?
Help me please.

**Comment by baopham** [comment]
**Get**

`$item->test->a` will not work. `$item->test` would be an array so try: `$item->test['a']`. 

**Update**

$item->test['a'] = 'something';
$item->save();

**Remove**

Removing nested object wasn't something I had in mind at the time I implemented `removeAttribute`. This can be an easy fix.

**Comment by raskalbass** [comment]
OK, get an array element works,
but update doesn't work:
```
$item->test['a'] = 'something';
$item->save();
```
throw `Indirect modification of overloaded property `
what wrong?)

remove nested also will be cool

**Comment by baopham** [comment]
```
$test = $item->test;
$test['a'] = 'something';
$item->test = $test;
$item->save();
```

**Comment by baopham** [comment]
Please try version `1.7.1` or if you are using v2, please try version `2.0.1`

**Comment by raskalbass** [comment]
trying  `$item->removeAttribute('test.a')` but seems that it is doesn work, just nothing happends, also no errors. 
but `echo $item->test['a']` give value, so shema is ok.

**Comment by baopham** [comment]
are you sure you have updated to the correct version? Ensure to run `composer update`

**Comment by baopham** [comment]
```php
$item->removeAttribute('test.a');
$item = Model::find(1);
print_r($item->test); // check if you still see `a`
```

**Comment by raskalbass** [comment]
Version correct - `Installing baopham/dynamodb (2.0.1)`
first i run
```
$item= Room::find(1); 
$item->test = ['a' => 'a', 'b' => 'b'];
$item->save();
```
then another
```
$item= Room::find(1); 
$item->removeAttribute('test.a');
$item= Room::find(1); 
print_r($item->test);
```
result
```
Array
(
    [a] => a
    [b] => b
)
```

if use just $item->removeAttribute('test') - test removed

**Comment by baopham** [comment]
Glad to hear you're using v2. Can you try again with the new version I just released: 2.0.2

**Comment by raskalbass** [comment]
All works fine! 
Tested `test.a` and `test[0]` for lists.
Thanks a lot!

**Comment by baopham** [comment]
awesome 👍
